
import os
import shutil
import time


#名稱(取出來較好變換)
sort_rime="sort_rime"
rime_files_1="注音洋蔥純注音版"
rime_files_2="注音洋蔥plus版"
rime_files_3="注音洋蔥mixin版"
rime_files_4="注音洋蔥雙拼版"
rime_files_5="地球拼音洋蔥mix-in版"
rime_ocm_folder="ocm"
rime_files_6=rime_ocm_folder+"/ocm_mount"
rime_files_7=rime_ocm_folder+"/ocm_plus"
rime_files_8=rime_ocm_folder+"/ocm_mixin"
rime_files_9="洋蔥行列30"
rime_files_10="洋蔥行列10"
the_name="電腦RIME方案"


#※新增資料夾(多層目錄, 如前一層data資料夾不存在, 將自動新增)※
os.makedirs("./"+sort_rime+"/"+rime_files_1+"/", exist_ok=True)
os.makedirs("./"+sort_rime+"/"+rime_files_2+"/opencc/", exist_ok=True)
os.makedirs("./"+sort_rime+"/"+rime_files_3+"/opencc/", exist_ok=True)
os.makedirs("./"+sort_rime+"/"+rime_files_4+"/opencc/", exist_ok=True)
os.makedirs("./"+sort_rime+"/"+rime_files_5+"/opencc/", exist_ok=True)
os.makedirs("./"+sort_rime+"/"+rime_files_6+"/", exist_ok=True)
os.makedirs("./"+sort_rime+"/"+rime_files_7+"/opencc/", exist_ok=True)
os.makedirs("./"+sort_rime+"/"+rime_files_8+"/opencc/", exist_ok=True)
os.makedirs("./"+sort_rime+"/"+rime_files_9+"/", exist_ok=True)
os.makedirs("./"+sort_rime+"/"+rime_files_10+"/", exist_ok=True)


#複製檔案(注音洋蔥純注音版)
shutil.copyfile("./rimefiles/essay-zh-hant-mc.txt", "./"+sort_rime+"/"+rime_files_1+"/essay-zh-hant-mc.txt")
shutil.copyfile("./rimefiles/bopomo_onion_phrase.txt", "./"+sort_rime+"/"+rime_files_1+"/bopomo_onion_phrase.txt")
shutil.copyfile("./rimefiles/bopomo_onion_symbols.yaml", "./"+sort_rime+"/"+rime_files_1+"/bopomo_onion_symbols.yaml")
shutil.copyfile("./rimefiles/bopomo_onion.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_1+"/bopomo_onion.extended.dict.yaml")
shutil.copyfile("./rimefiles/bopomo_onion.schema.yaml", "./"+sort_rime+"/"+rime_files_1+"/bopomo_onion.schema.yaml")
shutil.copyfile("./rimefiles/cangjie5.dict.yaml", "./"+sort_rime+"/"+rime_files_1+"/cangjie5.dict.yaml")
shutil.copyfile("./rimefiles/cangjie5.schema.yaml", "./"+sort_rime+"/"+rime_files_1+"/cangjie5.schema.yaml")
shutil.copyfile("./rimefiles/terra_pinyin_onion_add.dict.yaml", "./"+sort_rime+"/"+rime_files_1+"/terra_pinyin_onion_add.dict.yaml")
shutil.copyfile("./rimefiles/terra_pinyin_onion.dict.yaml", "./"+sort_rime+"/"+rime_files_1+"/terra_pinyin_onion.dict.yaml")
shutil.copyfile("./rimefiles/mixin_bpmf.dict.yaml", "./"+sort_rime+"/"+rime_files_1+"/mixin_bpmf.dict.yaml")

shutil.copyfile("./rimefiles/各方案default.custom/注音洋蔥純注音版_custom/default.custom.yaml", "./"+sort_rime+"/"+rime_files_1+"/default.custom.yaml")


#複製檔案(注音洋蔥plus版)
shutil.copyfile("./rimefiles/essay-zh-hant-mc.txt", "./"+sort_rime+"/"+rime_files_2+"/essay-zh-hant-mc.txt")
shutil.copyfile("./rimefiles/essay-jp-onion.txt", "./"+sort_rime+"/"+rime_files_2+"/essay-jp-onion.txt")
shutil.copyfile("./rimefiles/essay-kr-hanja.txt", "./"+sort_rime+"/"+rime_files_2+"/essay-kr-hanja.txt")
shutil.copyfile("./rimefiles/allbpm.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/allbpm.dict.yaml")
shutil.copyfile("./rimefiles/allbpm.schema.yaml", "./"+sort_rime+"/"+rime_files_2+"/allbpm.schema.yaml")
shutil.copyfile("./rimefiles/bopomo_onionplus_space.schema.yaml", "./"+sort_rime+"/"+rime_files_2+"/bopomo_onionplus_space.schema.yaml")
shutil.copyfile("./rimefiles/bopomo_onionplus_phrase.txt", "./"+sort_rime+"/"+rime_files_2+"/bopomo_onionplus_phrase.txt")
shutil.copyfile("./rimefiles/lua_custom_phrase.txt", "./"+sort_rime+"/"+rime_files_2+"/lua_custom_phrase.txt")
shutil.copyfile("./rimefiles/bopomo_onionplus.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/bopomo_onionplus.extended.dict.yaml")
shutil.copyfile("./rimefiles/bopomo_onionplus.schema.yaml", "./"+sort_rime+"/"+rime_files_2+"/bopomo_onionplus.schema.yaml")
shutil.copyfile("./rimefiles/cangjie5.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/cangjie5.dict.yaml")
shutil.copyfile("./rimefiles/cangjie5.schema.yaml", "./"+sort_rime+"/"+rime_files_2+"/cangjie5.schema.yaml")
shutil.copyfile("./rimefiles/cyrillic.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/cyrillic.dict.yaml")
shutil.copyfile("./rimefiles/cyrillic.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/cyrillic.extended.dict.yaml")
shutil.copyfile("./rimefiles/cyrillic.schema.yaml", "./"+sort_rime+"/"+rime_files_2+"/cyrillic.schema.yaml")

# shutil.copyfile("./rimefiles/easy_en_super.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/easy_en_super.dict.yaml")
# shutil.copyfile("./rimefiles/easy_en_super_original.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/easy_en_super_original.dict.yaml")
# shutil.copyfile("./rimefiles/easy_en_super.schema.yaml", "./"+sort_rime+"/"+rime_files_2+"/easy_en_super.schema.yaml")
shutil.copyfile("./rimefiles/easy_en_lcomment.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/easy_en_lcomment.dict.yaml")
shutil.copyfile("./rimefiles/easy_en_lcomment.schema.yaml", "./"+sort_rime+"/"+rime_files_2+"/easy_en_lcomment.schema.yaml")
shutil.copyfile("./rimefiles/easy_en_lower.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/easy_en_lower.dict.yaml")
shutil.copyfile("./rimefiles/easy_en_lower.schema.yaml", "./"+sort_rime+"/"+rime_files_2+"/easy_en_lower.schema.yaml")
shutil.copyfile("./rimefiles/easy_en_upper.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/easy_en_upper.dict.yaml")
shutil.copyfile("./rimefiles/easy_en_upper.schema.yaml", "./"+sort_rime+"/"+rime_files_2+"/easy_en_upper.schema.yaml")

shutil.copyfile("./rimefiles/element_bopomo.yaml", "./"+sort_rime+"/"+rime_files_2+"/element_bopomo.yaml")
shutil.copyfile("./rimefiles/fullshape.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/fullshape.extended.dict.yaml")
shutil.copyfile("./rimefiles/fullshape.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/fullshape.dict.yaml")
shutil.copyfile("./rimefiles/fullshape.schema.yaml", "./"+sort_rime+"/"+rime_files_2+"/fullshape.schema.yaml")
shutil.copyfile("./rimefiles/greek.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/greek.dict.yaml")
shutil.copyfile("./rimefiles/greek.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/greek.extended.dict.yaml")
shutil.copyfile("./rimefiles/greek.schema.yaml", "./"+sort_rime+"/"+rime_files_2+"/greek.schema.yaml")
shutil.copyfile("./rimefiles/hangeul_phrase.txt", "./"+sort_rime+"/"+rime_files_2+"/hangeul_phrase.txt")
shutil.copyfile("./rimefiles/hangeul.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/hangeul.dict.yaml")
shutil.copyfile("./rimefiles/hangeul_hanja.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/hangeul_hanja.dict.yaml")
shutil.copyfile("./rimefiles/hangeul.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/hangeul.extended.dict.yaml")
shutil.copyfile("./rimefiles/hangeul.schema.yaml", "./"+sort_rime+"/"+rime_files_2+"/hangeul.schema.yaml")
shutil.copyfile("./rimefiles/hangeul_hnc.schema.yaml", "./"+sort_rime+"/"+rime_files_2+"/hangeul_hnc.schema.yaml")
shutil.copyfile("./rimefiles/hangeul_hnc.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/hangeul_hnc.extended.dict.yaml")
shutil.copyfile("./rimefiles/hangeul_hnc.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/hangeul_hnc.dict.yaml")
shutil.copyfile("./rimefiles/hangeul_hnc_hanja.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/hangeul_hnc_hanja.dict.yaml")
shutil.copyfile("./rimefiles/hangeul_hnc_phrase.txt", "./"+sort_rime+"/"+rime_files_2+"/hangeul_hnc_phrase.txt")
shutil.copyfile("./rimefiles/jpnin1_phrase.txt", "./"+sort_rime+"/"+rime_files_2+"/jpnin1_phrase.txt")
shutil.copyfile("./rimefiles/jpnin1.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/jpnin1.dict.yaml")
shutil.copyfile("./rimefiles/jpnin1_hw.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/jpnin1_hw.dict.yaml")
shutil.copyfile("./rimefiles/jpnin1.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/jpnin1.extended.dict.yaml")
shutil.copyfile("./rimefiles/jpnin1.schema.yaml", "./"+sort_rime+"/"+rime_files_2+"/jpnin1.schema.yaml")
shutil.copyfile("./rimefiles/latinin1.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/latinin1.dict.yaml")
shutil.copyfile("./rimefiles/latinin1.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/latinin1.extended.dict.yaml")
shutil.copyfile("./rimefiles/latinin1.schema.yaml", "./"+sort_rime+"/"+rime_files_2+"/latinin1.schema.yaml")
shutil.copyfile("./rimefiles/space.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/space.dict.yaml")
shutil.copyfile("./rimefiles/space_f.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/space_f.dict.yaml")

shutil.copyfile("./rimefiles/phrases.cht.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/phrases.cht.dict.yaml")
shutil.copyfile("./rimefiles/phrases.chtp.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/phrases.chtp.dict.yaml")
shutil.copyfile("./rimefiles/phrases.cyr_all.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/phrases.cyr_all.dict.yaml")
shutil.copyfile("./rimefiles/phrases.en_l_w.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/phrases.en_l_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.en_o_w.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/phrases.en_o_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.en_u_w.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/phrases.en_u_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.fs_all.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/phrases.fs_all.dict.yaml")
shutil.copyfile("./rimefiles/phrases.gr_all.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/phrases.gr_all.dict.yaml")
shutil.copyfile("./rimefiles/phrases.jp_hk.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/phrases.jp_hk.dict.yaml")
shutil.copyfile("./rimefiles/phrases.jp_hk_more.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/phrases.jp_hk_more.dict.yaml")
shutil.copyfile("./rimefiles/phrases.jp_hkk.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/phrases.jp_hkk.dict.yaml")
shutil.copyfile("./rimefiles/phrases.jp_hkkseg.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/phrases.jp_hkkseg.dict.yaml")
# shutil.copyfile("./rimefiles/phrases.jp_hkup_w.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/phrases.jp_hkup_w.dict.yaml")
# shutil.copyfile("./rimefiles/phrases.jp_hkmoreup_w.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/phrases.jp_hkmoreup_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.kr_more.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/phrases.kr_more.dict.yaml")
shutil.copyfile("./rimefiles/phrases.la_py_w.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/phrases.la_py_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.la_eu_w.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/phrases.la_eu_w.dict.yaml")

shutil.copyfile("./rimefiles/punct_bopomo.yaml", "./"+sort_rime+"/"+rime_files_2+"/punct_bopomo.yaml")
shutil.copyfile("./rimefiles/rime.lua", "./"+sort_rime+"/"+rime_files_2+"/rime.lua")
shutil.copytree("./rimefiles/lua/", "./"+sort_rime+"/"+rime_files_2+"/lua/")
shutil.copyfile("./rimefiles/symbols_bpmf.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/symbols_bpmf.dict.yaml")
shutil.copyfile("./rimefiles/symbols_bpmf.schema.yaml", "./"+sort_rime+"/"+rime_files_2+"/symbols_bpmf.schema.yaml")
shutil.copyfile("./rimefiles/terra_pinyin_onion_add.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/terra_pinyin_onion_add.dict.yaml")
shutil.copyfile("./rimefiles/terra_pinyin_onion.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/terra_pinyin_onion.dict.yaml")
shutil.copyfile("./rimefiles/mixin_bpmf.dict.yaml", "./"+sort_rime+"/"+rime_files_2+"/mixin_bpmf.dict.yaml")

shutil.copyfile("./rimefiles/各方案default.custom/注音洋蔥plus版_custom/default.custom.yaml", "./"+sort_rime+"/"+rime_files_2+"/default.custom.yaml")

shutil.copyfile("./rimefiles/opencc/back_mark.json", "./"+sort_rime+"/"+rime_files_2+"/opencc/back_mark.json")
shutil.copyfile("./rimefiles/opencc/back_mark_series.json", "./"+sort_rime+"/"+rime_files_2+"/opencc/back_mark_series.json")
shutil.copyfile("./rimefiles/opencc/back_mark_script.txt", "./"+sort_rime+"/"+rime_files_2+"/opencc/back_mark_script.txt")
shutil.copyfile("./rimefiles/opencc/back_mark_table.txt", "./"+sort_rime+"/"+rime_files_2+"/opencc/back_mark_table.txt")
shutil.copyfile("./rimefiles/opencc/bpm_moedict_big5e_hkscs_jis.json", "./"+sort_rime+"/"+rime_files_2+"/opencc/bpm_moedict_big5e_hkscs_jis.json")
shutil.copyfile("./rimefiles/opencc/bpm_moedict_big5e_hkscs_jis.txt", "./"+sort_rime+"/"+rime_files_2+"/opencc/bpm_moedict_big5e_hkscs_jis.txt")
shutil.copyfile("./rimefiles/opencc/emoji_t.json", "./"+sort_rime+"/"+rime_files_2+"/opencc/emoji_t.json")
shutil.copyfile("./rimefiles/opencc/emoji_t.txt", "./"+sort_rime+"/"+rime_files_2+"/opencc/emoji_t.txt")
shutil.copyfile("./rimefiles/opencc/ocm_moedict_big5e_hkscs_jis.json", "./"+sort_rime+"/"+rime_files_2+"/opencc/ocm_moedict_big5e_hkscs_jis.json")
shutil.copyfile("./rimefiles/opencc/ocm_moedict_big5e_hkscs_jis.txt", "./"+sort_rime+"/"+rime_files_2+"/opencc/ocm_moedict_big5e_hkscs_jis.txt")
shutil.copyfile("./rimefiles/opencc/punct_mark.json", "./"+sort_rime+"/"+rime_files_2+"/opencc/punct_mark.json")
shutil.copyfile("./rimefiles/opencc/punct_mark.txt", "./"+sort_rime+"/"+rime_files_2+"/opencc/punct_mark.txt")

# shutil.copytree("./rimefiles/custom檔_舊版防崩潰/plus注音_防崩潰：Win必加，Mac勿加/", "./"+sort_rime+"/"+rime_files_2+"/plus注音_防崩潰：Win必加，Mac勿加/")
# shutil.copyfile("./rimefiles/custom檔_舊版防崩潰/easy_en_super_防崩潰：Win必加，Mac勿加/easy_en_super.custom.yaml", "./"+sort_rime+"/"+rime_files_2+"/plus注音_防崩潰：Win必加，Mac勿加/easy_en_super.custom.yaml")
# shutil.copyfile("./rimefiles/custom檔_舊版防崩潰/easy_en_lower_防崩潰：Win必加，Mac勿加/easy_en_lower.custom.yaml", "./"+sort_rime+"/"+rime_files_2+"/plus注音_防崩潰：Win必加，Mac勿加/easy_en_lower.custom.yaml")
# shutil.copytree("./rimefiles/custom檔_日語jpnin1精簡/jpnin1只出假名修改檔/", "./"+sort_rime+"/"+rime_files_2+"/jpnin1只出假名修改檔/")
# shutil.copytree("./rimefiles/custom檔_日語jpnin1精簡/jpnin1精簡轉寫修改檔/", "./"+sort_rime+"/"+rime_files_2+"/jpnin1精簡轉寫修改檔/")
shutil.copytree("./rimefiles/custom檔_日語jpnin1精簡/", "./"+sort_rime+"/"+rime_files_2+"/custom檔_日語jpnin1精簡/")


#複製檔案(注音洋蔥mixin版)
shutil.copyfile("./rimefiles/essay-zh-hant-mc-mixin.txt", "./"+sort_rime+"/"+rime_files_3+"/essay-zh-hant-mc-mixin.txt")
shutil.copyfile("./rimefiles/essay-jp-onion.txt", "./"+sort_rime+"/"+rime_files_3+"/essay-jp-onion.txt")
shutil.copyfile("./rimefiles/allbpm.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/allbpm.dict.yaml")
shutil.copyfile("./rimefiles/allbpm.schema.yaml", "./"+sort_rime+"/"+rime_files_3+"/allbpm.schema.yaml")
shutil.copyfile("./rimefiles/bo_mixin_jp.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/bo_mixin_jp.dict.yaml")
shutil.copyfile("./rimefiles/bo_mixin_kr.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/bo_mixin_kr.dict.yaml")
shutil.copyfile("./rimefiles/bo_mixin_kr_hnc.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/bo_mixin_kr_hnc.dict.yaml")
shutil.copyfile("./rimefiles/bo_mixin_la.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/bo_mixin_la.dict.yaml")
shutil.copyfile("./rimefiles/bo_mixin_en.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/bo_mixin_en.dict.yaml")
shutil.copyfile("./rimefiles/bo_mixin_phrase.txt", "./"+sort_rime+"/"+rime_files_3+"/bo_mixin_phrase.txt")
shutil.copyfile("./rimefiles/lua_custom_phrase.txt", "./"+sort_rime+"/"+rime_files_3+"/lua_custom_phrase.txt")
shutil.copyfile("./rimefiles/bo_mixin.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/bo_mixin.extended.dict.yaml")
shutil.copyfile("./rimefiles/bo_mixin1.schema.yaml", "./"+sort_rime+"/"+rime_files_3+"/bo_mixin1.schema.yaml")
shutil.copyfile("./rimefiles/bo_mixin2.schema.yaml", "./"+sort_rime+"/"+rime_files_3+"/bo_mixin2.schema.yaml")
shutil.copyfile("./rimefiles/bo_mixin3.schema.yaml", "./"+sort_rime+"/"+rime_files_3+"/bo_mixin3.schema.yaml")
shutil.copyfile("./rimefiles/bo_mixin4.schema.yaml", "./"+sort_rime+"/"+rime_files_3+"/bo_mixin4.schema.yaml")
shutil.copyfile("./rimefiles/cangjie5.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/cangjie5.dict.yaml")
shutil.copyfile("./rimefiles/cangjie5.schema.yaml", "./"+sort_rime+"/"+rime_files_3+"/cangjie5.schema.yaml")
shutil.copyfile("./rimefiles/cyrillic.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/cyrillic.dict.yaml")
shutil.copyfile("./rimefiles/cyrillic.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/cyrillic.extended.dict.yaml")
shutil.copyfile("./rimefiles/cyrillic.schema.yaml", "./"+sort_rime+"/"+rime_files_3+"/cyrillic.schema.yaml")
shutil.copyfile("./rimefiles/space.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/space.dict.yaml")
shutil.copyfile("./rimefiles/space_f.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/space_f.dict.yaml")

# shutil.copyfile("./rimefiles/easy_en_super.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/easy_en_super.dict.yaml")
# shutil.copyfile("./rimefiles/easy_en_super_original.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/easy_en_super_original.dict.yaml")
# shutil.copyfile("./rimefiles/easy_en_super.schema.yaml", "./"+sort_rime+"/"+rime_files_3+"/easy_en_super.schema.yaml")
shutil.copyfile("./rimefiles/easy_en_lcomment.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/easy_en_lcomment.dict.yaml")
shutil.copyfile("./rimefiles/easy_en_lcomment.schema.yaml", "./"+sort_rime+"/"+rime_files_3+"/easy_en_lcomment.schema.yaml")
shutil.copyfile("./rimefiles/easy_en_lower.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/easy_en_lower.dict.yaml")
shutil.copyfile("./rimefiles/easy_en_lower.schema.yaml", "./"+sort_rime+"/"+rime_files_3+"/easy_en_lower.schema.yaml")
shutil.copyfile("./rimefiles/easy_en_upper.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/easy_en_upper.dict.yaml")
shutil.copyfile("./rimefiles/easy_en_upper.schema.yaml", "./"+sort_rime+"/"+rime_files_3+"/easy_en_upper.schema.yaml")

shutil.copyfile("./rimefiles/element_bopomo.yaml", "./"+sort_rime+"/"+rime_files_3+"/element_bopomo.yaml")
shutil.copyfile("./rimefiles/fullshape.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/fullshape.extended.dict.yaml")
shutil.copyfile("./rimefiles/fullshape.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/fullshape.dict.yaml")
shutil.copyfile("./rimefiles/fullshape.schema.yaml", "./"+sort_rime+"/"+rime_files_3+"/fullshape.schema.yaml")
shutil.copyfile("./rimefiles/greek.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/greek.dict.yaml")
shutil.copyfile("./rimefiles/greek.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/greek.extended.dict.yaml")
shutil.copyfile("./rimefiles/greek.schema.yaml", "./"+sort_rime+"/"+rime_files_3+"/greek.schema.yaml")

shutil.copyfile("./rimefiles/phrases.cht_en_w.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/phrases.cht_en_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.cht.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/phrases.cht.dict.yaml")
shutil.copyfile("./rimefiles/phrases.chtp.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/phrases.chtp.dict.yaml")
shutil.copyfile("./rimefiles/phrases.cyr_all.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/phrases.cyr_all.dict.yaml")
shutil.copyfile("./rimefiles/phrases.en_l_w.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/phrases.en_l_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.en_o_w.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/phrases.en_o_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.en_u_w.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/phrases.en_u_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.fs_all.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/phrases.fs_all.dict.yaml")
shutil.copyfile("./rimefiles/phrases.gr_all.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/phrases.gr_all.dict.yaml")
shutil.copyfile("./rimefiles/phrases.jp_hk_more.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/phrases.jp_hk_more.dict.yaml")
shutil.copyfile("./rimefiles/phrases.jp_hk.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/phrases.jp_hk.dict.yaml")
shutil.copyfile("./rimefiles/phrases.jp_hkkreduce.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/phrases.jp_hkkreduce.dict.yaml")
shutil.copyfile("./rimefiles/phrases.kr_more.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/phrases.kr_more.dict.yaml")
shutil.copyfile("./rimefiles/phrases.kr.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/phrases.kr.dict.yaml")
shutil.copyfile("./rimefiles/phrases.la_py_w.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/phrases.la_py_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.la_eu_w.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/phrases.la_eu_w.dict.yaml")

shutil.copyfile("./rimefiles/punct_bopomo.yaml", "./"+sort_rime+"/"+rime_files_3+"/punct_bopomo.yaml")
shutil.copyfile("./rimefiles/rime.lua", "./"+sort_rime+"/"+rime_files_3+"/rime.lua")
shutil.copytree("./rimefiles/lua/", "./"+sort_rime+"/"+rime_files_3+"/lua/")
shutil.copyfile("./rimefiles/symbols_bpmf.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/symbols_bpmf.dict.yaml")
shutil.copyfile("./rimefiles/symbols_bpmf.schema.yaml", "./"+sort_rime+"/"+rime_files_3+"/symbols_bpmf.schema.yaml")
shutil.copyfile("./rimefiles/terra_pinyin_onion_add.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/terra_pinyin_onion_add.dict.yaml")
shutil.copyfile("./rimefiles/terra_pinyin_onion.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/terra_pinyin_onion.dict.yaml")
shutil.copyfile("./rimefiles/mixin_bpmf.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/mixin_bpmf.dict.yaml")

shutil.copyfile("./rimefiles/jpnin1_phrase.txt", "./"+sort_rime+"/"+rime_files_3+"/jpnin1_phrase.txt")
shutil.copyfile("./rimefiles/jpnin1.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/jpnin1.dict.yaml")
shutil.copyfile("./rimefiles/jpnin1_hw.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/jpnin1_hw.dict.yaml")
shutil.copyfile("./rimefiles/jpnin1.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/jpnin1.extended.dict.yaml")
shutil.copyfile("./rimefiles/jpnin1.schema.yaml", "./"+sort_rime+"/"+rime_files_3+"/jpnin1.schema.yaml")
shutil.copyfile("./rimefiles/phrases.jp_hkk.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/phrases.jp_hkk.dict.yaml")
shutil.copyfile("./rimefiles/phrases.jp_hkkseg.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/phrases.jp_hkkseg.dict.yaml")
# shutil.copyfile("./rimefiles/phrases.jp_hkup_w.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/phrases.jp_hkup_w.dict.yaml")
# shutil.copyfile("./rimefiles/phrases.jp_hkmoreup_w.dict.yaml", "./"+sort_rime+"/"+rime_files_3+"/phrases.jp_hkmoreup_w.dict.yaml")

shutil.copyfile("./rimefiles/各方案default.custom/注音洋蔥mixin版_custom/default.custom.yaml", "./"+sort_rime+"/"+rime_files_3+"/default.custom.yaml")

shutil.copyfile("./rimefiles/opencc/back_mark.json", "./"+sort_rime+"/"+rime_files_3+"/opencc/back_mark.json")
shutil.copyfile("./rimefiles/opencc/back_mark_series.json", "./"+sort_rime+"/"+rime_files_3+"/opencc/back_mark_series.json")
shutil.copyfile("./rimefiles/opencc/back_mark_script.txt", "./"+sort_rime+"/"+rime_files_3+"/opencc/back_mark_script.txt")
shutil.copyfile("./rimefiles/opencc/back_mark_table.txt", "./"+sort_rime+"/"+rime_files_3+"/opencc/back_mark_table.txt")
shutil.copyfile("./rimefiles/opencc/bpm_moedict_big5e_hkscs_jis.json", "./"+sort_rime+"/"+rime_files_3+"/opencc/bpm_moedict_big5e_hkscs_jis.json")
shutil.copyfile("./rimefiles/opencc/bpm_moedict_big5e_hkscs_jis.txt", "./"+sort_rime+"/"+rime_files_3+"/opencc/bpm_moedict_big5e_hkscs_jis.txt")
shutil.copyfile("./rimefiles/opencc/emoji_t.json", "./"+sort_rime+"/"+rime_files_3+"/opencc/emoji_t.json")
shutil.copyfile("./rimefiles/opencc/emoji_t.txt", "./"+sort_rime+"/"+rime_files_3+"/opencc/emoji_t.txt")
shutil.copyfile("./rimefiles/opencc/ocm_moedict_big5e_hkscs_jis.json", "./"+sort_rime+"/"+rime_files_3+"/opencc/ocm_moedict_big5e_hkscs_jis.json")
shutil.copyfile("./rimefiles/opencc/ocm_moedict_big5e_hkscs_jis.txt", "./"+sort_rime+"/"+rime_files_3+"/opencc/ocm_moedict_big5e_hkscs_jis.txt")
shutil.copyfile("./rimefiles/opencc/punct_mark.json", "./"+sort_rime+"/"+rime_files_3+"/opencc/punct_mark.json")
shutil.copyfile("./rimefiles/opencc/punct_mark.txt", "./"+sort_rime+"/"+rime_files_3+"/opencc/punct_mark.txt")

shutil.copytree("./rimefiles/custom檔_注音mixin版兩行同顯/", "./"+sort_rime+"/"+rime_files_3+"/custom檔_注音mixin版兩行同顯/")

# shutil.copytree("./rimefiles/custom檔_注音mixin版舊版同顯/mixin注音_同顯1修改檔(Mac)(fcitx5-rime)/", "./"+sort_rime+"/"+rime_files_3+"/mixin注音_同顯1修改檔(Mac)(fcitx5-rime)/")
# shutil.copytree("./rimefiles/custom檔_注音mixin版舊版同顯/mixin注音_同顯2修改檔(Mac)(fcitx5-rime)/", "./"+sort_rime+"/"+rime_files_3+"/mixin注音_同顯2修改檔(Mac)(fcitx5-rime)/")
# shutil.copytree("./rimefiles/custom檔_注音mixin版舊版同顯/mixin注音_同顯1修改檔(Win)/", "./"+sort_rime+"/"+rime_files_3+"/mixin注音_同顯1修改檔(Win)/")
# shutil.copytree("./rimefiles/custom檔_注音mixin版舊版同顯/mixin注音_同顯2修改檔(Win)/", "./"+sort_rime+"/"+rime_files_3+"/mixin注音_同顯2修改檔(Win)/")

# shutil.copyfile("./rimefiles/custom檔_舊版防崩潰/easy_en_super_防崩潰：Win必加，Mac勿加/easy_en_super.custom.yaml", "./"+sort_rime+"/"+rime_files_3+"/mixin注音_同顯1修改檔(Win)/easy_en_super.custom.yaml")
# shutil.copyfile("./rimefiles/custom檔_舊版防崩潰/easy_en_super_防崩潰：Win必加，Mac勿加/easy_en_super.custom.yaml", "./"+sort_rime+"/"+rime_files_3+"/mixin注音_同顯2修改檔(Win)/easy_en_super.custom.yaml")
# shutil.copyfile("./rimefiles/custom檔_舊版防崩潰/easy_en_lower_防崩潰：Win必加，Mac勿加/easy_en_lower.custom.yaml", "./"+sort_rime+"/"+rime_files_3+"/mixin注音_同顯1修改檔(Win)/easy_en_lower.custom.yaml")
# shutil.copyfile("./rimefiles/custom檔_舊版防崩潰/easy_en_lower_防崩潰：Win必加，Mac勿加/easy_en_lower.custom.yaml", "./"+sort_rime+"/"+rime_files_3+"/mixin注音_同顯2修改檔(Win)/easy_en_lower.custom.yaml")


#複製檔案(注音洋蔥雙拼版)
shutil.copyfile("./rimefiles/essay-zh-hant-mc.txt", "./"+sort_rime+"/"+rime_files_4+"/essay-zh-hant-mc.txt")
shutil.copyfile("./rimefiles/bopomo_onion_double.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_4+"/bopomo_onion_double.extended.dict.yaml")
shutil.copyfile("./rimefiles/bopomo_onion_double.schema.yaml", "./"+sort_rime+"/"+rime_files_4+"/bopomo_onion_double.schema.yaml")
shutil.copyfile("./rimefiles/bopomo_onion_double_t2.schema.yaml", "./"+sort_rime+"/"+rime_files_4+"/bopomo_onion_double_t2.schema.yaml")
shutil.copyfile("./rimefiles/bopomo_onion_double_phrase.txt", "./"+sort_rime+"/"+rime_files_4+"/bopomo_onion_double_phrase.txt")
shutil.copyfile("./rimefiles/cangjie5.dict.yaml", "./"+sort_rime+"/"+rime_files_4+"/cangjie5.dict.yaml")
shutil.copyfile("./rimefiles/cangjie5.schema.yaml", "./"+sort_rime+"/"+rime_files_4+"/cangjie5.schema.yaml")
shutil.copyfile("./rimefiles/rime.lua", "./"+sort_rime+"/"+rime_files_4+"/rime.lua")
shutil.copytree("./rimefiles/lua/", "./"+sort_rime+"/"+rime_files_4+"/lua/")
shutil.copyfile("./rimefiles/terra_pinyin_onion_add.dict.yaml", "./"+sort_rime+"/"+rime_files_4+"/terra_pinyin_onion_add.dict.yaml")
shutil.copyfile("./rimefiles/terra_pinyin_onion.dict.yaml", "./"+sort_rime+"/"+rime_files_4+"/terra_pinyin_onion.dict.yaml")
shutil.copyfile("./rimefiles/mixin_bpmf.dict.yaml", "./"+sort_rime+"/"+rime_files_4+"/mixin_bpmf.dict.yaml")
shutil.copyfile("./rimefiles/phrases.chtp.dict.yaml", "./"+sort_rime+"/"+rime_files_4+"/phrases.chtp.dict.yaml")
shutil.copyfile("./rimefiles/symbols_bpmf.dict.yaml", "./"+sort_rime+"/"+rime_files_4+"/symbols_bpmf.dict.yaml")
shutil.copyfile("./rimefiles/symbols_bpmf_double.schema.yaml", "./"+sort_rime+"/"+rime_files_4+"/symbols_bpmf_double.schema.yaml")
shutil.copyfile("./rimefiles/element_bopomo_double.yaml", "./"+sort_rime+"/"+rime_files_4+"/element_bopomo_double.yaml")
shutil.copyfile("./rimefiles/punct_bopomo_double.yaml", "./"+sort_rime+"/"+rime_files_4+"/punct_bopomo_double.yaml")
shutil.copyfile("./rimefiles/lua_custom_phrase.txt", "./"+sort_rime+"/"+rime_files_4+"/lua_custom_phrase.txt")

shutil.copyfile("./rimefiles/opencc/back_mark.json", "./"+sort_rime+"/"+rime_files_4+"/opencc/back_mark.json")
shutil.copyfile("./rimefiles/opencc/back_mark_series.json", "./"+sort_rime+"/"+rime_files_4+"/opencc/back_mark_series.json")
shutil.copyfile("./rimefiles/opencc/back_mark_script.txt", "./"+sort_rime+"/"+rime_files_4+"/opencc/back_mark_script.txt")
shutil.copyfile("./rimefiles/opencc/back_mark_table.txt", "./"+sort_rime+"/"+rime_files_4+"/opencc/back_mark_table.txt")
shutil.copyfile("./rimefiles/opencc/punct_mark.json", "./"+sort_rime+"/"+rime_files_4+"/opencc/punct_mark.json")
shutil.copyfile("./rimefiles/opencc/punct_mark.txt", "./"+sort_rime+"/"+rime_files_4+"/opencc/punct_mark.txt")
shutil.copyfile("./rimefiles/opencc/emoji_t.json", "./"+sort_rime+"/"+rime_files_4+"/opencc/emoji_t.json")
shutil.copyfile("./rimefiles/opencc/emoji_t.txt", "./"+sort_rime+"/"+rime_files_4+"/opencc/emoji_t.txt")

shutil.copyfile("./rimefiles/各方案default.custom/注音洋蔥雙拼版_custom/default.custom.yaml", "./"+sort_rime+"/"+rime_files_4+"/default.custom.yaml")

# shutil.copytree("./rimefiles/custom檔_雙拼注音不開頭簡拼/", "./"+sort_rime+"/"+rime_files_4+"/custom檔_雙拼注音不開頭簡拼/")
shutil.copytree("./rimefiles/雙拼注音鍵位說明圖示/", "./"+sort_rime+"/"+rime_files_4+"/雙拼注音鍵位說明圖示/")


#複製檔案(地球拼音洋蔥mix-in版)
shutil.copyfile("./rimefiles/essay-zh-hant-mc-mixin.txt", "./"+sort_rime+"/"+rime_files_5+"/essay-zh-hant-mc-mixin.txt")
shutil.copyfile("./rimefiles/cangjie5.dict.yaml", "./"+sort_rime+"/"+rime_files_5+"/cangjie5.dict.yaml")
shutil.copyfile("./rimefiles/cangjie5.schema.yaml", "./"+sort_rime+"/"+rime_files_5+"/cangjie5.schema.yaml")
shutil.copyfile("./rimefiles/ocm_mixin_jp.dict.yaml", "./"+sort_rime+"/"+rime_files_5+"/ocm_mixin_jp.dict.yaml")
shutil.copyfile("./rimefiles/ocm_mixin_kr.dict.yaml", "./"+sort_rime+"/"+rime_files_5+"/ocm_mixin_kr.dict.yaml")
shutil.copyfile("./rimefiles/ocm_mixin_kr_hnc.dict.yaml", "./"+sort_rime+"/"+rime_files_5+"/ocm_mixin_kr_hnc.dict.yaml")
shutil.copyfile("./rimefiles/ocm_mixin_la.dict.yaml", "./"+sort_rime+"/"+rime_files_5+"/ocm_mixin_la.dict.yaml")

shutil.copyfile("./rimefiles/phrases.cht_en_w.dict.yaml", "./"+sort_rime+"/"+rime_files_5+"/phrases.cht_en_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.cht.dict.yaml", "./"+sort_rime+"/"+rime_files_5+"/phrases.cht.dict.yaml")
shutil.copyfile("./rimefiles/phrases.chtp.dict.yaml", "./"+sort_rime+"/"+rime_files_5+"/phrases.chtp.dict.yaml")
shutil.copyfile("./rimefiles/phrases.en_l_w.dict.yaml", "./"+sort_rime+"/"+rime_files_5+"/phrases.en_l_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.en_o_w.dict.yaml", "./"+sort_rime+"/"+rime_files_5+"/phrases.en_o_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.en_u_w.dict.yaml", "./"+sort_rime+"/"+rime_files_5+"/phrases.en_u_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.jp_hk.dict.yaml", "./"+sort_rime+"/"+rime_files_5+"/phrases.jp_hk.dict.yaml")
shutil.copyfile("./rimefiles/phrases.jp_hkkreduce.dict.yaml", "./"+sort_rime+"/"+rime_files_5+"/phrases.jp_hkkreduce.dict.yaml")
shutil.copyfile("./rimefiles/phrases.kr.dict.yaml", "./"+sort_rime+"/"+rime_files_5+"/phrases.kr.dict.yaml")
shutil.copyfile("./rimefiles/phrases.la_py_w.dict.yaml", "./"+sort_rime+"/"+rime_files_5+"/phrases.la_py_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.la_eu_w.dict.yaml", "./"+sort_rime+"/"+rime_files_5+"/phrases.la_eu_w.dict.yaml")

shutil.copyfile("./rimefiles/terra_pinyin_onion_add.dict.yaml", "./"+sort_rime+"/"+rime_files_5+"/terra_pinyin_onion_add.dict.yaml")
shutil.copyfile("./rimefiles/terra_pinyin_onion.dict.yaml", "./"+sort_rime+"/"+rime_files_5+"/terra_pinyin_onion.dict.yaml")
shutil.copyfile("./rimefiles/terra_pinyin_onion.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_5+"/terra_pinyin_onion.extended.dict.yaml")
shutil.copyfile("./rimefiles/terra_pinyin_onion.schema.yaml", "./"+sort_rime+"/"+rime_files_5+"/terra_pinyin_onion.schema.yaml")

shutil.copyfile("./rimefiles/各方案default.custom/地球拼音洋蔥mix-in版_custom/default.custom.yaml", "./"+sort_rime+"/"+rime_files_5+"/default.custom.yaml")

shutil.copyfile("./rimefiles/opencc/back_mark_ocm.json", "./"+sort_rime+"/"+rime_files_5+"/opencc/back_mark_ocm.json")
shutil.copyfile("./rimefiles/opencc/back_mark_ocm.txt", "./"+sort_rime+"/"+rime_files_5+"/opencc/back_mark_ocm.txt")


#複製檔案(ocm_mount)
shutil.copyfile("./rimefiles/essay-zh-hant-mc.txt", "./"+sort_rime+"/"+rime_files_6+"/essay-zh-hant-mc.txt")
shutil.copyfile("./rimefiles/Mount_bopomo.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_6+"/Mount_bopomo.extended.dict.yaml")
shutil.copyfile("./rimefiles/Mount_bopomo.schema.yaml", "./"+sort_rime+"/"+rime_files_6+"/Mount_bopomo.schema.yaml")

shutil.copyfile("./rimefiles/Mount_ocm.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_6+"/Mount_ocm.extended.dict.yaml")
shutil.copyfile("./rimefiles/Mount_ocm.schema.yaml", "./"+sort_rime+"/"+rime_files_6+"/Mount_ocm.schema.yaml")
shutil.copyfile("./rimefiles/Mount_ocm_encoder.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_6+"/Mount_ocm_encoder.extended.dict.yaml")
shutil.copyfile("./rimefiles/Mount_ocm_encoder.schema.yaml", "./"+sort_rime+"/"+rime_files_6+"/Mount_ocm_encoder.schema.yaml")
shutil.copyfile("./rimefiles/Mount_ocm_encoder.custom.yaml", "./"+sort_rime+"/"+rime_files_6+"/Mount_ocm_encoder.custom.yaml")
shutil.copyfile("./rimefiles/element_ocm.yaml", "./"+sort_rime+"/"+rime_files_6+"/element_ocm.yaml")

shutil.copyfile("./rimefiles/punct_ovff.dict.yaml", "./"+sort_rime+"/"+rime_files_6+"/punct_ovff.dict.yaml")
shutil.copyfile("./rimefiles/punct_ovff.schema.yaml", "./"+sort_rime+"/"+rime_files_6+"/punct_ovff.schema.yaml")
shutil.copyfile("./rimefiles/symbols_ocm.dict.yaml", "./"+sort_rime+"/"+rime_files_6+"/symbols_ocm.dict.yaml")
shutil.copyfile("./rimefiles/symbols_ocm.schema.yaml", "./"+sort_rime+"/"+rime_files_6+"/symbols_ocm.schema.yaml")

shutil.copyfile("./rimefiles/terra_pinyin_onion_add.dict.yaml", "./"+sort_rime+"/"+rime_files_6+"/terra_pinyin_onion_add.dict.yaml")
shutil.copyfile("./rimefiles/terra_pinyin_onion.dict.yaml", "./"+sort_rime+"/"+rime_files_6+"/terra_pinyin_onion.dict.yaml")
shutil.copyfile("./rimefiles/ocm_tc_mc.dict.yaml", "./"+sort_rime+"/"+rime_files_6+"/ocm_tc_mc.dict.yaml")
shutil.copyfile("./rimefiles/uniabcdword.dict.yaml", "./"+sort_rime+"/"+rime_files_6+"/uniabcdword.dict.yaml")
shutil.copyfile("./rimefiles/kanaword.dict.yaml", "./"+sort_rime+"/"+rime_files_6+"/kanaword.dict.yaml")
shutil.copyfile("./rimefiles/phrases.ocmtc_essay_mc.dict.yaml", "./"+sort_rime+"/"+rime_files_6+"/phrases.ocmtc_essay_mc.dict.yaml")

shutil.copyfile("./rimefiles/rime.lua", "./"+sort_rime+"/"+rime_files_6+"/rime.lua")
shutil.copytree("./rimefiles/lua/", "./"+sort_rime+"/"+rime_files_6+"/lua/")

shutil.copyfile("./rimefiles/各方案default.custom/ocm_mount_custom/default.custom.yaml", "./"+sort_rime+"/"+rime_files_6+"/default.custom.yaml")


#複製檔案(ocm_plus)
shutil.copyfile("./rimefiles/essay-zh-hant-mc.txt", "./"+sort_rime+"/"+rime_files_7+"/essay-zh-hant-mc.txt")
shutil.copyfile("./rimefiles/allbpm.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/allbpm.dict.yaml")
shutil.copyfile("./rimefiles/allbpm.schema.yaml", "./"+sort_rime+"/"+rime_files_7+"/allbpm.schema.yaml")
shutil.copyfile("./rimefiles/cyrillic.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/cyrillic.dict.yaml")
shutil.copyfile("./rimefiles/cyrillic.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/cyrillic.extended.dict.yaml")

# shutil.copyfile("./rimefiles/easy_en_super.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/easy_en_super.dict.yaml")
# shutil.copyfile("./rimefiles/easy_en_super_original.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/easy_en_super_original.dict.yaml")
# shutil.copyfile("./rimefiles/easy_en_super.schema.yaml", "./"+sort_rime+"/"+rime_files_7+"/easy_en_super.schema.yaml")
shutil.copyfile("./rimefiles/easy_en_lcomment.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/easy_en_lcomment.dict.yaml")
shutil.copyfile("./rimefiles/easy_en_lcomment.schema.yaml", "./"+sort_rime+"/"+rime_files_7+"/easy_en_lcomment.schema.yaml")
shutil.copyfile("./rimefiles/easy_en_lower.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/easy_en_lower.dict.yaml")
shutil.copyfile("./rimefiles/easy_en_lower.schema.yaml", "./"+sort_rime+"/"+rime_files_7+"/easy_en_lower.schema.yaml")
shutil.copyfile("./rimefiles/easy_en_upper.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/easy_en_upper.dict.yaml")
shutil.copyfile("./rimefiles/easy_en_upper.schema.yaml", "./"+sort_rime+"/"+rime_files_7+"/easy_en_upper.schema.yaml")

shutil.copyfile("./rimefiles/fullshape.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/fullshape.extended.dict.yaml")
shutil.copyfile("./rimefiles/fullshape.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/fullshape.dict.yaml")
shutil.copyfile("./rimefiles/greek.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/greek.dict.yaml")
shutil.copyfile("./rimefiles/greek.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/greek.extended.dict.yaml")
shutil.copyfile("./rimefiles/Mount_bopomo.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/Mount_bopomo.extended.dict.yaml")
shutil.copyfile("./rimefiles/Mount_bopomo.schema.yaml", "./"+sort_rime+"/"+rime_files_7+"/Mount_bopomo.schema.yaml")
shutil.copyfile("./rimefiles/ocm_mixin_jp.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/ocm_mixin_jp.dict.yaml")
shutil.copyfile("./rimefiles/ocm_mixin_kr.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/ocm_mixin_kr.dict.yaml")
shutil.copyfile("./rimefiles/ocm_mixin_la.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/ocm_mixin_la.dict.yaml")
shutil.copyfile("./rimefiles/space_f.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/space_f.dict.yaml")

shutil.copyfile("./rimefiles/dif1_cy.schema.yaml", "./"+sort_rime+"/"+rime_files_7+"/dif1_cy.schema.yaml")
shutil.copyfile("./rimefiles/dif1_fs.schema.yaml", "./"+sort_rime+"/"+rime_files_7+"/dif1_fs.schema.yaml")
shutil.copyfile("./rimefiles/dif1_gr.schema.yaml", "./"+sort_rime+"/"+rime_files_7+"/dif1_gr.schema.yaml")
shutil.copyfile("./rimefiles/dif1_jp.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/dif1_jp.extended.dict.yaml")
shutil.copyfile("./rimefiles/dif1_jphi.schema.yaml", "./"+sort_rime+"/"+rime_files_7+"/dif1_jphi.schema.yaml")
shutil.copyfile("./rimefiles/dif1_jpka.schema.yaml", "./"+sort_rime+"/"+rime_files_7+"/dif1_jpka.schema.yaml")
shutil.copyfile("./rimefiles/dif1_kr.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/dif1_kr.extended.dict.yaml")
shutil.copyfile("./rimefiles/dif1_kr.schema.yaml", "./"+sort_rime+"/"+rime_files_7+"/dif1_kr.schema.yaml")
shutil.copyfile("./rimefiles/dif1_la.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/dif1_la.extended.dict.yaml")
shutil.copyfile("./rimefiles/dif1_la.schema.yaml", "./"+sort_rime+"/"+rime_files_7+"/dif1_la.schema.yaml")
shutil.copyfile("./rimefiles/dif1_phrase.txt", "./"+sort_rime+"/"+rime_files_7+"/dif1_phrase.txt")
shutil.copyfile("./rimefiles/lua_custom_phrase.txt", "./"+sort_rime+"/"+rime_files_7+"/lua_custom_phrase.txt")
shutil.copyfile("./rimefiles/dif1.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/dif1.extended.dict.yaml")
shutil.copyfile("./rimefiles/dif1.schema.yaml", "./"+sort_rime+"/"+rime_files_7+"/dif1.schema.yaml")

shutil.copyfile("./rimefiles/phrases.cyr_all.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/phrases.cyr_all.dict.yaml")
shutil.copyfile("./rimefiles/phrases.en_l_w.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/phrases.en_l_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.en_o_w.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/phrases.en_o_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.en_u_w.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/phrases.en_u_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.fs_all.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/phrases.fs_all.dict.yaml")
shutil.copyfile("./rimefiles/phrases.gr_all.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/phrases.gr_all.dict.yaml")
shutil.copyfile("./rimefiles/phrases.jp_hk_more.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/phrases.jp_hk_more.dict.yaml")
shutil.copyfile("./rimefiles/phrases.jp_hk.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/phrases.jp_hk.dict.yaml")
shutil.copyfile("./rimefiles/phrases.kr.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/phrases.kr.dict.yaml")
shutil.copyfile("./rimefiles/phrases.la_py_w.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/phrases.la_py_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.la_eu_w.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/phrases.la_eu_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.ocmtc_essay_mc.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/phrases.ocmtc_essay_mc.dict.yaml")

shutil.copyfile("./rimefiles/punct_ovff.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/punct_ovff.dict.yaml")
shutil.copyfile("./rimefiles/punct_ovff.schema.yaml", "./"+sort_rime+"/"+rime_files_7+"/punct_ovff.schema.yaml")
shutil.copyfile("./rimefiles/symbols_ocm.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/symbols_ocm.dict.yaml")
shutil.copyfile("./rimefiles/symbols_ocm.schema.yaml", "./"+sort_rime+"/"+rime_files_7+"/symbols_ocm.schema.yaml")

shutil.copyfile("./rimefiles/terra_pinyin_onion_add.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/terra_pinyin_onion_add.dict.yaml")
shutil.copyfile("./rimefiles/terra_pinyin_onion.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/terra_pinyin_onion.dict.yaml")
shutil.copyfile("./rimefiles/ocm_tc_mc.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/ocm_tc_mc.dict.yaml")
shutil.copyfile("./rimefiles/uniabcdword.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/uniabcdword.dict.yaml")

shutil.copyfile("./rimefiles/element_ocm.yaml", "./"+sort_rime+"/"+rime_files_7+"/element_ocm.yaml")
shutil.copyfile("./rimefiles/punct_ocm.yaml", "./"+sort_rime+"/"+rime_files_7+"/punct_ocm.yaml")
shutil.copyfile("./rimefiles/rime.lua", "./"+sort_rime+"/"+rime_files_7+"/rime.lua")
shutil.copytree("./rimefiles/lua/", "./"+sort_rime+"/"+rime_files_7+"/lua/")

shutil.copyfile("./rimefiles/各方案default.custom/ocm_plus_custom/default.custom.yaml", "./"+sort_rime+"/"+rime_files_7+"/default.custom.yaml")

shutil.copyfile("./rimefiles/opencc/back_mark.json", "./"+sort_rime+"/"+rime_files_7+"/opencc/back_mark.json")
shutil.copyfile("./rimefiles/opencc/back_mark_series.json", "./"+sort_rime+"/"+rime_files_7+"/opencc/back_mark_series.json")
shutil.copyfile("./rimefiles/opencc/back_mark_script.txt", "./"+sort_rime+"/"+rime_files_7+"/opencc/back_mark_script.txt")
shutil.copyfile("./rimefiles/opencc/back_mark_table.txt", "./"+sort_rime+"/"+rime_files_7+"/opencc/back_mark_table.txt")
shutil.copyfile("./rimefiles/opencc/emoji_t.json", "./"+sort_rime+"/"+rime_files_7+"/opencc/emoji_t.json")
shutil.copyfile("./rimefiles/opencc/emoji_t.txt", "./"+sort_rime+"/"+rime_files_7+"/opencc/emoji_t.txt")
shutil.copyfile("./rimefiles/opencc/ocm_moedict_big5e_hkscs_jis.json", "./"+sort_rime+"/"+rime_files_7+"/opencc/ocm_moedict_big5e_hkscs_jis.json")
shutil.copyfile("./rimefiles/opencc/ocm_moedict_big5e_hkscs_jis.txt", "./"+sort_rime+"/"+rime_files_7+"/opencc/ocm_moedict_big5e_hkscs_jis.txt")
shutil.copyfile("./rimefiles/opencc/punct_mark_plus.json", "./"+sort_rime+"/"+rime_files_7+"/opencc/punct_mark_plus.json")
shutil.copyfile("./rimefiles/opencc/punct_mark.txt", "./"+sort_rime+"/"+rime_files_7+"/opencc/punct_mark.txt")
shutil.copyfile("./rimefiles/opencc/punct_mark_plus.txt", "./"+sort_rime+"/"+rime_files_7+"/opencc/punct_mark_plus.txt")

shutil.copyfile("./rimefiles/jpnin1_phrase.txt", "./"+sort_rime+"/"+rime_files_7+"/jpnin1_phrase.txt")
shutil.copyfile("./rimefiles/jpnin1.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/jpnin1.dict.yaml")
shutil.copyfile("./rimefiles/jpnin1_hw.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/jpnin1_hw.dict.yaml")
shutil.copyfile("./rimefiles/jpnin1.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/jpnin1.extended.dict.yaml")
shutil.copyfile("./rimefiles/jpnin1.schema.yaml", "./"+sort_rime+"/"+rime_files_7+"/jpnin1.schema.yaml")
shutil.copyfile("./rimefiles/essay-jp-onion.txt", "./"+sort_rime+"/"+rime_files_7+"/essay-jp-onion.txt")
shutil.copyfile("./rimefiles/phrases.jp_hkk.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/phrases.jp_hkk.dict.yaml")
shutil.copyfile("./rimefiles/phrases.jp_hkkseg.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/phrases.jp_hkkseg.dict.yaml")
# shutil.copyfile("./rimefiles/phrases.jp_hkup_w.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/phrases.jp_hkup_w.dict.yaml")
# shutil.copyfile("./rimefiles/phrases.jp_hkmoreup_w.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/phrases.jp_hkmoreup_w.dict.yaml")
shutil.copyfile("./rimefiles/cangjie5.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/cangjie5.dict.yaml")
shutil.copyfile("./rimefiles/cangjie5.schema.yaml", "./"+sort_rime+"/"+rime_files_7+"/cangjie5.schema.yaml")
shutil.copyfile("./rimefiles/space.dict.yaml", "./"+sort_rime+"/"+rime_files_7+"/space.dict.yaml")


#複製檔案(ocm_mixin)
shutil.copyfile("./rimefiles/essay-zh-hant-mc.txt", "./"+sort_rime+"/"+rime_files_8+"/essay-zh-hant-mc.txt")
shutil.copyfile("./rimefiles/allbpm.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/allbpm.dict.yaml")
shutil.copyfile("./rimefiles/allbpm.schema.yaml", "./"+sort_rime+"/"+rime_files_8+"/allbpm.schema.yaml")
shutil.copyfile("./rimefiles/cyrillic.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/cyrillic.dict.yaml")
shutil.copyfile("./rimefiles/cyrillic.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/cyrillic.extended.dict.yaml")

# shutil.copyfile("./rimefiles/easy_en_super.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/easy_en_super.dict.yaml")
# shutil.copyfile("./rimefiles/easy_en_super_original.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/easy_en_super_original.dict.yaml")
# shutil.copyfile("./rimefiles/easy_en_super.schema.yaml", "./"+sort_rime+"/"+rime_files_8+"/easy_en_super.schema.yaml")
shutil.copyfile("./rimefiles/easy_en_lcomment.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/easy_en_lcomment.dict.yaml")
shutil.copyfile("./rimefiles/easy_en_lcomment.schema.yaml", "./"+sort_rime+"/"+rime_files_8+"/easy_en_lcomment.schema.yaml")
shutil.copyfile("./rimefiles/easy_en_lower.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/easy_en_lower.dict.yaml")
shutil.copyfile("./rimefiles/easy_en_lower.schema.yaml", "./"+sort_rime+"/"+rime_files_8+"/easy_en_lower.schema.yaml")
shutil.copyfile("./rimefiles/easy_en_upper.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/easy_en_upper.dict.yaml")
shutil.copyfile("./rimefiles/easy_en_upper.schema.yaml", "./"+sort_rime+"/"+rime_files_8+"/easy_en_upper.schema.yaml")

shutil.copyfile("./rimefiles/fullshape.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/fullshape.extended.dict.yaml")
shutil.copyfile("./rimefiles/fullshape.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/fullshape.dict.yaml")
shutil.copyfile("./rimefiles/greek.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/greek.dict.yaml")
shutil.copyfile("./rimefiles/greek.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/greek.extended.dict.yaml")
shutil.copyfile("./rimefiles/Mount_bopomo.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/Mount_bopomo.extended.dict.yaml")
shutil.copyfile("./rimefiles/Mount_bopomo.schema.yaml", "./"+sort_rime+"/"+rime_files_8+"/Mount_bopomo.schema.yaml")
shutil.copyfile("./rimefiles/Mount_ocm.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/Mount_ocm.extended.dict.yaml")
shutil.copyfile("./rimefiles/Mount_ocm.schema.yaml", "./"+sort_rime+"/"+rime_files_8+"/Mount_ocm.schema.yaml")
shutil.copyfile("./rimefiles/space_f.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/space_f.dict.yaml")

shutil.copyfile("./rimefiles/ocm_mixin_cyrillic.schema.yaml", "./"+sort_rime+"/"+rime_files_8+"/ocm_mixin_cyrillic.schema.yaml")
shutil.copyfile("./rimefiles/ocm_mixin_fullshape.schema.yaml", "./"+sort_rime+"/"+rime_files_8+"/ocm_mixin_fullshape.schema.yaml")
shutil.copyfile("./rimefiles/ocm_mixin_greek.schema.yaml", "./"+sort_rime+"/"+rime_files_8+"/ocm_mixin_greek.schema.yaml")
shutil.copyfile("./rimefiles/ocm_mixin_jp.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/ocm_mixin_jp.dict.yaml")
shutil.copyfile("./rimefiles/ocm_mixin_kr.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/ocm_mixin_kr.dict.yaml")
shutil.copyfile("./rimefiles/ocm_mixin_la.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/ocm_mixin_la.dict.yaml")
shutil.copyfile("./rimefiles/ocm_mixin_phrase.txt", "./"+sort_rime+"/"+rime_files_8+"/ocm_mixin_phrase.txt")
shutil.copyfile("./rimefiles/lua_custom_phrase.txt", "./"+sort_rime+"/"+rime_files_8+"/lua_custom_phrase.txt")
shutil.copyfile("./rimefiles/ocm_mixin.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/ocm_mixin.extended.dict.yaml")
shutil.copyfile("./rimefiles/ocm_mixin.schema.yaml", "./"+sort_rime+"/"+rime_files_8+"/ocm_mixin.schema.yaml")

shutil.copyfile("./rimefiles/punct_ovff.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/punct_ovff.dict.yaml")
shutil.copyfile("./rimefiles/punct_ovff.schema.yaml", "./"+sort_rime+"/"+rime_files_8+"/punct_ovff.schema.yaml")
shutil.copyfile("./rimefiles/symbols_ocm.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/symbols_ocm.dict.yaml")
shutil.copyfile("./rimefiles/symbols_ocm.schema.yaml", "./"+sort_rime+"/"+rime_files_8+"/symbols_ocm.schema.yaml")

shutil.copyfile("./rimefiles/terra_pinyin_onion_add.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/terra_pinyin_onion_add.dict.yaml")
shutil.copyfile("./rimefiles/terra_pinyin_onion.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/terra_pinyin_onion.dict.yaml")
shutil.copyfile("./rimefiles/ocm_tc_mc.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/ocm_tc_mc.dict.yaml")
shutil.copyfile("./rimefiles/kanaword.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/kanaword.dict.yaml")
shutil.copyfile("./rimefiles/uniabcdword.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/uniabcdword.dict.yaml")

shutil.copyfile("./rimefiles/phrases.cht_en_w.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/phrases.cht_en_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.cyr_all.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/phrases.cyr_all.dict.yaml")
shutil.copyfile("./rimefiles/phrases.en_l_w.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/phrases.en_l_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.en_o_w.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/phrases.en_o_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.en_u_w.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/phrases.en_u_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.fs_all.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/phrases.fs_all.dict.yaml")
shutil.copyfile("./rimefiles/phrases.gr_all.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/phrases.gr_all.dict.yaml")
shutil.copyfile("./rimefiles/phrases.jp_hk_more.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/phrases.jp_hk_more.dict.yaml")
shutil.copyfile("./rimefiles/phrases.jp_hk.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/phrases.jp_hk.dict.yaml")
shutil.copyfile("./rimefiles/phrases.jp_hkk.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/phrases.jp_hkk.dict.yaml")
shutil.copyfile("./rimefiles/phrases.kr_more.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/phrases.kr_more.dict.yaml")
shutil.copyfile("./rimefiles/phrases.kr.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/phrases.kr.dict.yaml")
shutil.copyfile("./rimefiles/phrases.la_py_w.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/phrases.la_py_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.la_eu_w.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/phrases.la_eu_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.ocmtc_essay_mc.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/phrases.ocmtc_essay_mc.dict.yaml")

shutil.copyfile("./rimefiles/element_ocm.yaml", "./"+sort_rime+"/"+rime_files_8+"/element_ocm.yaml")
shutil.copyfile("./rimefiles/punct_ocm.yaml", "./"+sort_rime+"/"+rime_files_8+"/punct_ocm.yaml")
# shutil.copyfile("./rimefiles/ocm_mixin_lua/rime.lua", "./"+sort_rime+"/"+rime_files_8+"/rime.lua")
shutil.copyfile("./rimefiles/rime.lua", "./"+sort_rime+"/"+rime_files_8+"/rime.lua")
shutil.copytree("./rimefiles/lua/", "./"+sort_rime+"/"+rime_files_8+"/lua/")

shutil.copyfile("./rimefiles/各方案default.custom/ocm_mixin_custom/default.custom.yaml", "./"+sort_rime+"/"+rime_files_8+"/default.custom.yaml")

shutil.copyfile("./rimefiles/opencc/back_mark.json", "./"+sort_rime+"/"+rime_files_8+"/opencc/back_mark.json")
shutil.copyfile("./rimefiles/opencc/back_mark_series.json", "./"+sort_rime+"/"+rime_files_8+"/opencc/back_mark_series.json")
shutil.copyfile("./rimefiles/opencc/back_mark_script.txt", "./"+sort_rime+"/"+rime_files_8+"/opencc/back_mark_script.txt")
shutil.copyfile("./rimefiles/opencc/back_mark_table.txt", "./"+sort_rime+"/"+rime_files_8+"/opencc/back_mark_table.txt")
# shutil.copyfile("./rimefiles/opencc/back_mark_ocm.json", "./"+sort_rime+"/"+rime_files_8+"/opencc/back_mark_ocm.json")
# shutil.copyfile("./rimefiles/opencc/back_mark_ocm.txt", "./"+sort_rime+"/"+rime_files_8+"/opencc/back_mark_ocm.txt")
shutil.copyfile("./rimefiles/opencc/emoji_t.json", "./"+sort_rime+"/"+rime_files_8+"/opencc/emoji_t.json")
shutil.copyfile("./rimefiles/opencc/emoji_t.txt", "./"+sort_rime+"/"+rime_files_8+"/opencc/emoji_t.txt")
shutil.copyfile("./rimefiles/opencc/ocm_moedict_big5e_hkscs_jis.json", "./"+sort_rime+"/"+rime_files_8+"/opencc/ocm_moedict_big5e_hkscs_jis.json")
shutil.copyfile("./rimefiles/opencc/ocm_moedict_big5e_hkscs_jis.txt", "./"+sort_rime+"/"+rime_files_8+"/opencc/ocm_moedict_big5e_hkscs_jis.txt")
shutil.copyfile("./rimefiles/opencc/punct_mark_plus.json", "./"+sort_rime+"/"+rime_files_8+"/opencc/punct_mark_plus.json")
shutil.copyfile("./rimefiles/opencc/punct_mark.txt", "./"+sort_rime+"/"+rime_files_8+"/opencc/punct_mark.txt")
shutil.copyfile("./rimefiles/opencc/punct_mark_plus.txt", "./"+sort_rime+"/"+rime_files_8+"/opencc/punct_mark_plus.txt")

shutil.copyfile("./rimefiles/jpnin1_phrase.txt", "./"+sort_rime+"/"+rime_files_8+"/jpnin1_phrase.txt")
shutil.copyfile("./rimefiles/jpnin1.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/jpnin1.dict.yaml")
shutil.copyfile("./rimefiles/jpnin1_hw.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/jpnin1_hw.dict.yaml")
shutil.copyfile("./rimefiles/jpnin1.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/jpnin1.extended.dict.yaml")
shutil.copyfile("./rimefiles/jpnin1.schema.yaml", "./"+sort_rime+"/"+rime_files_8+"/jpnin1.schema.yaml")
shutil.copyfile("./rimefiles/essay-jp-onion.txt", "./"+sort_rime+"/"+rime_files_8+"/essay-jp-onion.txt")
shutil.copyfile("./rimefiles/phrases.jp_hkkseg.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/phrases.jp_hkkseg.dict.yaml")
# shutil.copyfile("./rimefiles/phrases.jp_hkup_w.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/phrases.jp_hkup_w.dict.yaml")
# shutil.copyfile("./rimefiles/phrases.jp_hkmoreup_w.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/phrases.jp_hkmoreup_w.dict.yaml")
shutil.copyfile("./rimefiles/cangjie5.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/cangjie5.dict.yaml")
shutil.copyfile("./rimefiles/cangjie5.schema.yaml", "./"+sort_rime+"/"+rime_files_8+"/cangjie5.schema.yaml")
shutil.copyfile("./rimefiles/space.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/space.dict.yaml")

shutil.copyfile("./rimefiles/symbols-mark.dict.yaml", "./"+sort_rime+"/"+rime_files_8+"/symbols-mark.dict.yaml")
shutil.copyfile("./rimefiles/symbols-mark.schema.yaml", "./"+sort_rime+"/"+rime_files_8+"/symbols-mark.schema.yaml")


#複製檔案(洋蔥行列30)
shutil.copyfile("./rimefiles/essay-zh-hant-mc.txt", "./"+sort_rime+"/"+rime_files_9+"/essay-zh-hant-mc.txt")
shutil.copyfile("./rimefiles/Mount_bopomo.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_9+"/Mount_bopomo.extended.dict.yaml")
shutil.copyfile("./rimefiles/Mount_bopomo.schema.yaml", "./"+sort_rime+"/"+rime_files_9+"/Mount_bopomo.schema.yaml")
shutil.copyfile("./rimefiles/terra_pinyin_onion_add.dict.yaml", "./"+sort_rime+"/"+rime_files_9+"/terra_pinyin_onion_add.dict.yaml")
shutil.copyfile("./rimefiles/terra_pinyin_onion.dict.yaml", "./"+sort_rime+"/"+rime_files_9+"/terra_pinyin_onion.dict.yaml")

shutil.copyfile("./rimefiles/onion-array30.schema.yaml", "./"+sort_rime+"/"+rime_files_9+"/onion-array30.schema.yaml")
shutil.copyfile("./rimefiles/onion-array30-wsymbols.schema.yaml", "./"+sort_rime+"/"+rime_files_9+"/onion-array30-wsymbols.schema.yaml")
shutil.copyfile("./rimefiles/onion-array30.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_9+"/onion-array30.extended.dict.yaml")
shutil.copyfile("./rimefiles/onion-array30-wsymbols.dict.yaml", "./"+sort_rime+"/"+rime_files_9+"/onion-array30-wsymbols.dict.yaml")
shutil.copyfile("./rimefiles/onion-array30-special.dict.yaml", "./"+sort_rime+"/"+rime_files_9+"/onion-array30-special.dict.yaml")
shutil.copyfile("./rimefiles/onion-array30-shortcode.dict.yaml", "./"+sort_rime+"/"+rime_files_9+"/onion-array30-shortcode.dict.yaml")
shutil.copyfile("./rimefiles/onion-array30-phrases.dict.yaml", "./"+sort_rime+"/"+rime_files_9+"/onion-array30-phrases.dict.yaml")
shutil.copyfile("./rimefiles/onion-array30-generally.dict.yaml", "./"+sort_rime+"/"+rime_files_9+"/onion-array30-generally.dict.yaml")

shutil.copyfile("./rimefiles/rime.lua", "./"+sort_rime+"/"+rime_files_9+"/rime.lua")
shutil.copytree("./rimefiles/lua/", "./"+sort_rime+"/"+rime_files_9+"/lua/")

shutil.copytree("./rimefiles/行列30碼表_20230211版/", "./"+sort_rime+"/"+rime_files_9+"/行列30碼表_20230211版/")

shutil.copyfile("./rimefiles/各方案default.custom/洋蔥行列30_custom/default.custom.yaml", "./"+sort_rime+"/"+rime_files_9+"/default.custom.yaml")


#複製檔案(洋蔥行列10)
shutil.copyfile("./rimefiles/essay-zh-hant-mc.txt", "./"+sort_rime+"/"+rime_files_10+"/essay-zh-hant-mc.txt")
shutil.copyfile("./rimefiles/Mount_bopomo.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_10+"/Mount_bopomo.extended.dict.yaml")
shutil.copyfile("./rimefiles/Mount_bopomo.schema.yaml", "./"+sort_rime+"/"+rime_files_10+"/Mount_bopomo.schema.yaml")
shutil.copyfile("./rimefiles/terra_pinyin_onion_add.dict.yaml", "./"+sort_rime+"/"+rime_files_10+"/terra_pinyin_onion_add.dict.yaml")
shutil.copyfile("./rimefiles/terra_pinyin_onion.dict.yaml", "./"+sort_rime+"/"+rime_files_10+"/terra_pinyin_onion.dict.yaml")

shutil.copyfile("./rimefiles/onion-array10.schema.yaml", "./"+sort_rime+"/"+rime_files_10+"/onion-array10.schema.yaml")
shutil.copyfile("./rimefiles/onion-array10.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_10+"/onion-array10.extended.dict.yaml")
shutil.copyfile("./rimefiles/onion-array10-symbols.dict.yaml", "./"+sort_rime+"/"+rime_files_10+"/onion-array10-symbols.dict.yaml")
shutil.copyfile("./rimefiles/onion-array10-symbols-prefix.dict.yaml", "./"+sort_rime+"/"+rime_files_10+"/onion-array10-symbols-prefix.dict.yaml")
shutil.copyfile("./rimefiles/onion-array10-generally-a.dict.yaml", "./"+sort_rime+"/"+rime_files_10+"/onion-array10-generally-a.dict.yaml")
shutil.copyfile("./rimefiles/onion-array10-generally-b.dict.yaml", "./"+sort_rime+"/"+rime_files_10+"/onion-array10-generally-b.dict.yaml")
shutil.copyfile("./rimefiles/onion-array10-generally-c.dict.yaml", "./"+sort_rime+"/"+rime_files_10+"/onion-array10-generally-c.dict.yaml")
shutil.copyfile("./rimefiles/phrases.ocmtc_essay_mc.dict.yaml", "./"+sort_rime+"/"+rime_files_10+"/phrases.ocmtc_essay_mc.dict.yaml")

shutil.copyfile("./rimefiles/rime.lua", "./"+sort_rime+"/"+rime_files_10+"/rime.lua")
shutil.copytree("./rimefiles/lua/", "./"+sort_rime+"/"+rime_files_10+"/lua/")

shutil.copyfile("./rimefiles/onion-array10-and-bpmf.schema.yaml", "./"+sort_rime+"/"+rime_files_10+"/onion-array10-and-bpmf.schema.yaml")
shutil.copyfile("./rimefiles/bopomo_onion_phrase.txt", "./"+sort_rime+"/"+rime_files_10+"/bopomo_onion_phrase.txt")
shutil.copyfile("./rimefiles/bopomo_onion_symbols.yaml", "./"+sort_rime+"/"+rime_files_10+"/bopomo_onion_symbols.yaml")
shutil.copyfile("./rimefiles/bopomo_onion.extended.dict.yaml", "./"+sort_rime+"/"+rime_files_10+"/bopomo_onion.extended.dict.yaml")
shutil.copyfile("./rimefiles/bopomo_onion.schema.yaml", "./"+sort_rime+"/"+rime_files_10+"/bopomo_onion.schema.yaml")
shutil.copyfile("./rimefiles/cangjie5.dict.yaml", "./"+sort_rime+"/"+rime_files_10+"/cangjie5.dict.yaml")
shutil.copyfile("./rimefiles/cangjie5.schema.yaml", "./"+sort_rime+"/"+rime_files_10+"/cangjie5.schema.yaml")
shutil.copyfile("./rimefiles/mixin_bpmf.dict.yaml", "./"+sort_rime+"/"+rime_files_10+"/mixin_bpmf.dict.yaml")

shutil.copyfile("./rimefiles/各方案default.custom/洋蔥行列10_custom/default.custom.yaml", "./"+sort_rime+"/"+rime_files_10+"/default.custom.yaml")


#其他
shutil.copytree("./rimefiles/其他/", "./"+sort_rime+"/其他/")

# shutil.copytree("./rimefiles/其他/OpenCC_ocd_64位元/", "./"+sort_rime+"/ocm/OpenCC_ocd_64位元/")
# shutil.copytree("./rimefiles/custom檔_舊版防崩潰/ocm_防崩潰：Win必加，Mac勿加/", "./"+sort_rime+"/ocm/ocm_防崩潰：Win必加，Mac勿加/")
# shutil.copyfile("./rimefiles/custom檔_舊版防崩潰/easy_en_super_防崩潰：Win必加，Mac勿加/easy_en_super.custom.yaml", "./"+sort_rime+"/ocm/ocm_防崩潰：Win必加，Mac勿加/easy_en_super.custom.yaml")
# shutil.copyfile("./rimefiles/custom檔_舊版防崩潰/easy_en_lower_防崩潰：Win必加，Mac勿加/easy_en_lower.custom.yaml", "./"+sort_rime+"/ocm/ocm_防崩潰：Win必加，Mac勿加/easy_en_lower.custom.yaml")


#主程式
shutil.copytree("./rimefiles/主程式/", "./"+sort_rime+"/主程式/")


#增加日期
localtime=time.strftime("%Y%m%d", time.localtime())

os.rename("./"+sort_rime+"/"+rime_files_1+"/", "./"+sort_rime+"/"+rime_files_1+"_"+localtime)
os.rename("./"+sort_rime+"/"+rime_files_2+"/", "./"+sort_rime+"/"+rime_files_2+"_"+localtime)
os.rename("./"+sort_rime+"/"+rime_files_3+"/", "./"+sort_rime+"/"+rime_files_3+"_"+localtime)
os.rename("./"+sort_rime+"/"+rime_files_4+"/", "./"+sort_rime+"/"+rime_files_4+"_"+localtime)
os.rename("./"+sort_rime+"/"+rime_files_5+"/", "./"+sort_rime+"/"+rime_files_5+"_"+localtime)

os.rename("./"+sort_rime+"/"+rime_files_6+"/", "./"+sort_rime+"/"+rime_files_6+"_"+localtime)
os.rename("./"+sort_rime+"/"+rime_files_7+"/", "./"+sort_rime+"/"+rime_files_7+"_"+localtime)
os.rename("./"+sort_rime+"/"+rime_files_8+"/", "./"+sort_rime+"/"+rime_files_8+"_"+localtime)
os.rename("./"+sort_rime+"/"+rime_ocm_folder+"/", "./"+sort_rime+"/"+rime_ocm_folder+"_"+localtime)

os.rename("./"+sort_rime+"/"+rime_files_9+"/", "./"+sort_rime+"/"+rime_files_9+"_"+localtime)
os.rename("./"+sort_rime+"/"+rime_files_10+"/", "./"+sort_rime+"/"+rime_files_10+"_"+localtime)

os.rename("./"+sort_rime+"/", "./"+the_name+"_"+localtime)



