
import os
import shutil
import time


#名稱(取出來較好變換)
sort_rime="sort_rime_allx9"
rime_files="rime＜allin1＞"
the_name="電腦RIME方案＜allin1＞"


#※新增資料夾(多層目錄, 如前一層data資料夾不存在, 將自動新增)※
os.makedirs("./"+sort_rime+"/"+rime_files+"/opencc/", exist_ok=True)


#複製檔案(注音洋蔥純注音版)
shutil.copyfile("./rimefiles/essay-zh-hant-mc.txt", "./"+sort_rime+"/"+rime_files+"/essay-zh-hant-mc.txt")
shutil.copyfile("./rimefiles/bopomo_onion_phrase.txt", "./"+sort_rime+"/"+rime_files+"/bopomo_onion_phrase.txt")
shutil.copyfile("./rimefiles/bopomo_onion_symbols.yaml", "./"+sort_rime+"/"+rime_files+"/bopomo_onion_symbols.yaml")
shutil.copyfile("./rimefiles/bopomo_onion.extended.dict.yaml", "./"+sort_rime+"/"+rime_files+"/bopomo_onion.extended.dict.yaml")
shutil.copyfile("./rimefiles/bopomo_onion.schema.yaml", "./"+sort_rime+"/"+rime_files+"/bopomo_onion.schema.yaml")
shutil.copyfile("./rimefiles/cangjie5.dict.yaml", "./"+sort_rime+"/"+rime_files+"/cangjie5.dict.yaml")
shutil.copyfile("./rimefiles/cangjie5.schema.yaml", "./"+sort_rime+"/"+rime_files+"/cangjie5.schema.yaml")
shutil.copyfile("./rimefiles/terra_pinyin_onion_add.dict.yaml", "./"+sort_rime+"/"+rime_files+"/terra_pinyin_onion_add.dict.yaml")
shutil.copyfile("./rimefiles/terra_pinyin_onion.dict.yaml", "./"+sort_rime+"/"+rime_files+"/terra_pinyin_onion.dict.yaml")
shutil.copyfile("./rimefiles/mixin_bpmf.dict.yaml", "./"+sort_rime+"/"+rime_files+"/mixin_bpmf.dict.yaml")


#複製檔案(注音洋蔥plus版)
shutil.copyfile("./rimefiles/essay-jp-onion.txt", "./"+sort_rime+"/"+rime_files+"/essay-jp-onion.txt")
shutil.copyfile("./rimefiles/essay-kr-hanja.txt", "./"+sort_rime+"/"+rime_files+"/essay-kr-hanja.txt")
shutil.copyfile("./rimefiles/allbpm.dict.yaml", "./"+sort_rime+"/"+rime_files+"/allbpm.dict.yaml")
shutil.copyfile("./rimefiles/allbpm.schema.yaml", "./"+sort_rime+"/"+rime_files+"/allbpm.schema.yaml")
shutil.copyfile("./rimefiles/bopomo_onionplus_space.schema.yaml", "./"+sort_rime+"/"+rime_files+"/bopomo_onionplus_space.schema.yaml")
shutil.copyfile("./rimefiles/bopomo_onionplus_phrase.txt", "./"+sort_rime+"/"+rime_files+"/bopomo_onionplus_phrase.txt")
shutil.copyfile("./rimefiles/lua_custom_phrase.txt", "./"+sort_rime+"/"+rime_files+"/lua_custom_phrase.txt")
shutil.copyfile("./rimefiles/bopomo_onionplus.extended.dict.yaml", "./"+sort_rime+"/"+rime_files+"/bopomo_onionplus.extended.dict.yaml")
shutil.copyfile("./rimefiles/bopomo_onionplus.schema.yaml", "./"+sort_rime+"/"+rime_files+"/bopomo_onionplus.schema.yaml")
shutil.copyfile("./rimefiles/cyrillic.dict.yaml", "./"+sort_rime+"/"+rime_files+"/cyrillic.dict.yaml")
shutil.copyfile("./rimefiles/cyrillic.extended.dict.yaml", "./"+sort_rime+"/"+rime_files+"/cyrillic.extended.dict.yaml")
shutil.copyfile("./rimefiles/cyrillic.schema.yaml", "./"+sort_rime+"/"+rime_files+"/cyrillic.schema.yaml")
# shutil.copyfile("./rimefiles/easy_en_super.dict.yaml", "./"+sort_rime+"/"+rime_files+"/easy_en_super.dict.yaml")
# shutil.copyfile("./rimefiles/easy_en_super_original.dict.yaml", "./"+sort_rime+"/"+rime_files+"/easy_en_super_original.dict.yaml")
# shutil.copyfile("./rimefiles/easy_en_super.schema.yaml", "./"+sort_rime+"/"+rime_files+"/easy_en_super.schema.yaml")
shutil.copyfile("./rimefiles/easy_en_lcomment.dict.yaml", "./"+sort_rime+"/"+rime_files+"/easy_en_lcomment.dict.yaml")
shutil.copyfile("./rimefiles/easy_en_lcomment.schema.yaml", "./"+sort_rime+"/"+rime_files+"/easy_en_lcomment.schema.yaml")
shutil.copyfile("./rimefiles/easy_en_lower.dict.yaml", "./"+sort_rime+"/"+rime_files+"/easy_en_lower.dict.yaml")
shutil.copyfile("./rimefiles/easy_en_lower.schema.yaml", "./"+sort_rime+"/"+rime_files+"/easy_en_lower.schema.yaml")
shutil.copyfile("./rimefiles/easy_en_upper.dict.yaml", "./"+sort_rime+"/"+rime_files+"/easy_en_upper.dict.yaml")
shutil.copyfile("./rimefiles/easy_en_upper.schema.yaml", "./"+sort_rime+"/"+rime_files+"/easy_en_upper.schema.yaml")
shutil.copyfile("./rimefiles/element_bopomo.yaml", "./"+sort_rime+"/"+rime_files+"/element_bopomo.yaml")
shutil.copyfile("./rimefiles/fullshape.extended.dict.yaml", "./"+sort_rime+"/"+rime_files+"/fullshape.extended.dict.yaml")
shutil.copyfile("./rimefiles/fullshape.dict.yaml", "./"+sort_rime+"/"+rime_files+"/fullshape.dict.yaml")
shutil.copyfile("./rimefiles/fullshape.schema.yaml", "./"+sort_rime+"/"+rime_files+"/fullshape.schema.yaml")
shutil.copyfile("./rimefiles/greek.dict.yaml", "./"+sort_rime+"/"+rime_files+"/greek.dict.yaml")
shutil.copyfile("./rimefiles/greek.extended.dict.yaml", "./"+sort_rime+"/"+rime_files+"/greek.extended.dict.yaml")
shutil.copyfile("./rimefiles/greek.schema.yaml", "./"+sort_rime+"/"+rime_files+"/greek.schema.yaml")
shutil.copyfile("./rimefiles/hangeul_phrase.txt", "./"+sort_rime+"/"+rime_files+"/hangeul_phrase.txt")
shutil.copyfile("./rimefiles/hangeul.dict.yaml", "./"+sort_rime+"/"+rime_files+"/hangeul.dict.yaml")
shutil.copyfile("./rimefiles/hangeul_hanja.dict.yaml", "./"+sort_rime+"/"+rime_files+"/hangeul_hanja.dict.yaml")
shutil.copyfile("./rimefiles/hangeul.extended.dict.yaml", "./"+sort_rime+"/"+rime_files+"/hangeul.extended.dict.yaml")
shutil.copyfile("./rimefiles/hangeul.schema.yaml", "./"+sort_rime+"/"+rime_files+"/hangeul.schema.yaml")
shutil.copyfile("./rimefiles/hangeul_hnc.schema.yaml", "./"+sort_rime+"/"+rime_files+"/hangeul_hnc.schema.yaml")
shutil.copyfile("./rimefiles/hangeul_hnc.extended.dict.yaml", "./"+sort_rime+"/"+rime_files+"/hangeul_hnc.extended.dict.yaml")
shutil.copyfile("./rimefiles/hangeul_hnc.dict.yaml", "./"+sort_rime+"/"+rime_files+"/hangeul_hnc.dict.yaml")
shutil.copyfile("./rimefiles/hangeul_hnc_hanja.dict.yaml", "./"+sort_rime+"/"+rime_files+"/hangeul_hnc_hanja.dict.yaml")
shutil.copyfile("./rimefiles/hangeul_hnc_phrase.txt", "./"+sort_rime+"/"+rime_files+"/hangeul_hnc_phrase.txt")
shutil.copyfile("./rimefiles/jpnin1_phrase.txt", "./"+sort_rime+"/"+rime_files+"/jpnin1_phrase.txt")
shutil.copyfile("./rimefiles/jpnin1.dict.yaml", "./"+sort_rime+"/"+rime_files+"/jpnin1.dict.yaml")
shutil.copyfile("./rimefiles/jpnin1_hw.dict.yaml", "./"+sort_rime+"/"+rime_files+"/jpnin1_hw.dict.yaml")
shutil.copyfile("./rimefiles/jpnin1.extended.dict.yaml", "./"+sort_rime+"/"+rime_files+"/jpnin1.extended.dict.yaml")
shutil.copyfile("./rimefiles/jpnin1.schema.yaml", "./"+sort_rime+"/"+rime_files+"/jpnin1.schema.yaml")
shutil.copyfile("./rimefiles/latinin1.dict.yaml", "./"+sort_rime+"/"+rime_files+"/latinin1.dict.yaml")
shutil.copyfile("./rimefiles/latinin1.extended.dict.yaml", "./"+sort_rime+"/"+rime_files+"/latinin1.extended.dict.yaml")
shutil.copyfile("./rimefiles/latinin1.schema.yaml", "./"+sort_rime+"/"+rime_files+"/latinin1.schema.yaml")
shutil.copyfile("./rimefiles/space.dict.yaml", "./"+sort_rime+"/"+rime_files+"/space.dict.yaml")
shutil.copyfile("./rimefiles/space_f.dict.yaml", "./"+sort_rime+"/"+rime_files+"/space_f.dict.yaml")
shutil.copyfile("./rimefiles/phrases.cht.dict.yaml", "./"+sort_rime+"/"+rime_files+"/phrases.cht.dict.yaml")
shutil.copyfile("./rimefiles/phrases.chtp.dict.yaml", "./"+sort_rime+"/"+rime_files+"/phrases.chtp.dict.yaml")
shutil.copyfile("./rimefiles/phrases.cyr_all.dict.yaml", "./"+sort_rime+"/"+rime_files+"/phrases.cyr_all.dict.yaml")
shutil.copyfile("./rimefiles/phrases.en_l_w.dict.yaml", "./"+sort_rime+"/"+rime_files+"/phrases.en_l_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.en_o_w.dict.yaml", "./"+sort_rime+"/"+rime_files+"/phrases.en_o_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.en_u_w.dict.yaml", "./"+sort_rime+"/"+rime_files+"/phrases.en_u_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.fs_all.dict.yaml", "./"+sort_rime+"/"+rime_files+"/phrases.fs_all.dict.yaml")
shutil.copyfile("./rimefiles/phrases.gr_all.dict.yaml", "./"+sort_rime+"/"+rime_files+"/phrases.gr_all.dict.yaml")
shutil.copyfile("./rimefiles/phrases.jp_hk.dict.yaml", "./"+sort_rime+"/"+rime_files+"/phrases.jp_hk.dict.yaml")
shutil.copyfile("./rimefiles/phrases.jp_hk_more.dict.yaml", "./"+sort_rime+"/"+rime_files+"/phrases.jp_hk_more.dict.yaml")
shutil.copyfile("./rimefiles/phrases.jp_hkk.dict.yaml", "./"+sort_rime+"/"+rime_files+"/phrases.jp_hkk.dict.yaml")
shutil.copyfile("./rimefiles/phrases.jp_hkkseg.dict.yaml", "./"+sort_rime+"/"+rime_files+"/phrases.jp_hkkseg.dict.yaml")
# shutil.copyfile("./rimefiles/phrases.jp_hkup_w.dict.yaml", "./"+sort_rime+"/"+rime_files+"/phrases.jp_hkup_w.dict.yaml")
# shutil.copyfile("./rimefiles/phrases.jp_hkmoreup_w.dict.yaml", "./"+sort_rime+"/"+rime_files+"/phrases.jp_hkmoreup_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.kr_more.dict.yaml", "./"+sort_rime+"/"+rime_files+"/phrases.kr_more.dict.yaml")
shutil.copyfile("./rimefiles/phrases.la_py_w.dict.yaml", "./"+sort_rime+"/"+rime_files+"/phrases.la_py_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.la_eu_w.dict.yaml", "./"+sort_rime+"/"+rime_files+"/phrases.la_eu_w.dict.yaml")
shutil.copyfile("./rimefiles/punct_bopomo.yaml", "./"+sort_rime+"/"+rime_files+"/punct_bopomo.yaml")
shutil.copyfile("./rimefiles/rime.lua", "./"+sort_rime+"/"+rime_files+"/rime.lua")
shutil.copytree("./rimefiles/lua/", "./"+sort_rime+"/"+rime_files+"/lua/")
shutil.copyfile("./rimefiles/symbols_bpmf.dict.yaml", "./"+sort_rime+"/"+rime_files+"/symbols_bpmf.dict.yaml")
shutil.copyfile("./rimefiles/symbols_bpmf.schema.yaml", "./"+sort_rime+"/"+rime_files+"/symbols_bpmf.schema.yaml")
shutil.copyfile("./rimefiles/opencc/back_mark.json", "./"+sort_rime+"/"+rime_files+"/opencc/back_mark.json")
shutil.copyfile("./rimefiles/opencc/back_mark_series.json", "./"+sort_rime+"/"+rime_files+"/opencc/back_mark_series.json")
shutil.copyfile("./rimefiles/opencc/back_mark_script.txt", "./"+sort_rime+"/"+rime_files+"/opencc/back_mark_script.txt")
shutil.copyfile("./rimefiles/opencc/back_mark_table.txt", "./"+sort_rime+"/"+rime_files+"/opencc/back_mark_table.txt")
shutil.copyfile("./rimefiles/opencc/bpm_moedict_big5e_hkscs_jis.json", "./"+sort_rime+"/"+rime_files+"/opencc/bpm_moedict_big5e_hkscs_jis.json")
shutil.copyfile("./rimefiles/opencc/bpm_moedict_big5e_hkscs_jis.txt", "./"+sort_rime+"/"+rime_files+"/opencc/bpm_moedict_big5e_hkscs_jis.txt")
shutil.copyfile("./rimefiles/opencc/emoji_t.json", "./"+sort_rime+"/"+rime_files+"/opencc/emoji_t.json")
shutil.copyfile("./rimefiles/opencc/emoji_t.txt", "./"+sort_rime+"/"+rime_files+"/opencc/emoji_t.txt")
shutil.copyfile("./rimefiles/opencc/ocm_moedict_big5e_hkscs_jis.json", "./"+sort_rime+"/"+rime_files+"/opencc/ocm_moedict_big5e_hkscs_jis.json")
shutil.copyfile("./rimefiles/opencc/ocm_moedict_big5e_hkscs_jis.txt", "./"+sort_rime+"/"+rime_files+"/opencc/ocm_moedict_big5e_hkscs_jis.txt")
shutil.copyfile("./rimefiles/opencc/punct_mark.json", "./"+sort_rime+"/"+rime_files+"/opencc/punct_mark.json")
shutil.copyfile("./rimefiles/opencc/punct_mark.txt", "./"+sort_rime+"/"+rime_files+"/opencc/punct_mark.txt")
# shutil.copytree("./rimefiles/custom檔_舊版防崩潰/plus注音_防崩潰：Win必加，Mac勿加/", "./"+sort_rime+"/"+rime_files+"/plus注音_防崩潰：Win必加，Mac勿加/")
# shutil.copyfile("./rimefiles/custom檔_舊版防崩潰/easy_en_super_防崩潰：Win必加，Mac勿加/easy_en_super.custom.yaml", "./"+sort_rime+"/"+rime_files+"/plus注音_防崩潰：Win必加，Mac勿加/easy_en_super.custom.yaml")
# shutil.copyfile("./rimefiles/custom檔_舊版防崩潰/easy_en_lower_防崩潰：Win必加，Mac勿加/easy_en_lower.custom.yaml", "./"+sort_rime+"/"+rime_files+"/plus注音_防崩潰：Win必加，Mac勿加/easy_en_lower.custom.yaml")
# shutil.copytree("./rimefiles/custom檔_日語jpnin1精簡/jpnin1只出假名修改檔/", "./"+sort_rime+"/"+rime_files+"/jpnin1只出假名修改檔/")
# shutil.copytree("./rimefiles/custom檔_日語jpnin1精簡/jpnin1精簡轉寫修改檔/", "./"+sort_rime+"/"+rime_files+"/jpnin1精簡轉寫修改檔/")
shutil.copytree("./rimefiles/custom檔_日語jpnin1精簡/", "./"+sort_rime+"/"+rime_files+"/custom檔_日語jpnin1精簡/")


#複製檔案(注音洋蔥mixin版)
shutil.copyfile("./rimefiles/essay-zh-hant-mc-mixin.txt", "./"+sort_rime+"/"+rime_files+"/essay-zh-hant-mc-mixin.txt")
shutil.copyfile("./rimefiles/bo_mixin_jp.dict.yaml", "./"+sort_rime+"/"+rime_files+"/bo_mixin_jp.dict.yaml")
shutil.copyfile("./rimefiles/bo_mixin_kr.dict.yaml", "./"+sort_rime+"/"+rime_files+"/bo_mixin_kr.dict.yaml")
shutil.copyfile("./rimefiles/bo_mixin_kr_hnc.dict.yaml", "./"+sort_rime+"/"+rime_files+"/bo_mixin_kr_hnc.dict.yaml")
shutil.copyfile("./rimefiles/bo_mixin_la.dict.yaml", "./"+sort_rime+"/"+rime_files+"/bo_mixin_la.dict.yaml")
shutil.copyfile("./rimefiles/bo_mixin_en.dict.yaml", "./"+sort_rime+"/"+rime_files+"/bo_mixin_en.dict.yaml")
shutil.copyfile("./rimefiles/bo_mixin_phrase.txt", "./"+sort_rime+"/"+rime_files+"/bo_mixin_phrase.txt")
shutil.copyfile("./rimefiles/bo_mixin.extended.dict.yaml", "./"+sort_rime+"/"+rime_files+"/bo_mixin.extended.dict.yaml")
shutil.copyfile("./rimefiles/bo_mixin1.schema.yaml", "./"+sort_rime+"/"+rime_files+"/bo_mixin1.schema.yaml")
shutil.copyfile("./rimefiles/bo_mixin2.schema.yaml", "./"+sort_rime+"/"+rime_files+"/bo_mixin2.schema.yaml")
shutil.copyfile("./rimefiles/bo_mixin3.schema.yaml", "./"+sort_rime+"/"+rime_files+"/bo_mixin3.schema.yaml")
shutil.copyfile("./rimefiles/bo_mixin4.schema.yaml", "./"+sort_rime+"/"+rime_files+"/bo_mixin4.schema.yaml")
shutil.copyfile("./rimefiles/phrases.cht_en_w.dict.yaml", "./"+sort_rime+"/"+rime_files+"/phrases.cht_en_w.dict.yaml")
shutil.copyfile("./rimefiles/phrases.jp_hkkreduce.dict.yaml", "./"+sort_rime+"/"+rime_files+"/phrases.jp_hkkreduce.dict.yaml")
shutil.copyfile("./rimefiles/phrases.kr.dict.yaml", "./"+sort_rime+"/"+rime_files+"/phrases.kr.dict.yaml")
shutil.copytree("./rimefiles/custom檔_注音mixin版兩行同顯/", "./"+sort_rime+"/"+rime_files+"/custom檔_注音mixin版兩行同顯/")
# shutil.copytree("./rimefiles/custom檔_注音mixin版舊版同顯/mixin注音_同顯1修改檔(Mac)(fcitx5-rime)/", "./"+sort_rime+"/"+rime_files+"/mixin注音_同顯1修改檔(Mac)(fcitx5-rime)/")
# shutil.copytree("./rimefiles/custom檔_注音mixin版舊版同顯/mixin注音_同顯2修改檔(Mac)(fcitx5-rime)/", "./"+sort_rime+"/"+rime_files+"/mixin注音_同顯2修改檔(Mac)(fcitx5-rime)/")
# shutil.copytree("./rimefiles/custom檔_注音mixin版舊版同顯/mixin注音_同顯1修改檔(Win)/", "./"+sort_rime+"/"+rime_files+"/mixin注音_同顯1修改檔(Win)/")
# shutil.copytree("./rimefiles/custom檔_注音mixin版舊版同顯/mixin注音_同顯2修改檔(Win)/", "./"+sort_rime+"/"+rime_files+"/mixin注音_同顯2修改檔(Win)/")
# shutil.copyfile("./rimefiles/custom檔_舊版防崩潰/easy_en_super_防崩潰：Win必加，Mac勿加/easy_en_super.custom.yaml", "./"+sort_rime+"/"+rime_files+"/mixin注音_同顯1修改檔(Win)/easy_en_super.custom.yaml")
# shutil.copyfile("./rimefiles/custom檔_舊版防崩潰/easy_en_super_防崩潰：Win必加，Mac勿加/easy_en_super.custom.yaml", "./"+sort_rime+"/"+rime_files+"/mixin注音_同顯2修改檔(Win)/easy_en_super.custom.yaml")
# shutil.copyfile("./rimefiles/custom檔_舊版防崩潰/easy_en_lower_防崩潰：Win必加，Mac勿加/easy_en_lower.custom.yaml", "./"+sort_rime+"/"+rime_files+"/mixin注音_同顯1修改檔(Win)/easy_en_lower.custom.yaml")
# shutil.copyfile("./rimefiles/custom檔_舊版防崩潰/easy_en_lower_防崩潰：Win必加，Mac勿加/easy_en_lower.custom.yaml", "./"+sort_rime+"/"+rime_files+"/mixin注音_同顯2修改檔(Win)/easy_en_lower.custom.yaml")


#複製檔案(注音洋蔥雙拼版)
shutil.copyfile("./rimefiles/bopomo_onion_double.extended.dict.yaml", "./"+sort_rime+"/"+rime_files+"/bopomo_onion_double.extended.dict.yaml")
shutil.copyfile("./rimefiles/bopomo_onion_double.schema.yaml", "./"+sort_rime+"/"+rime_files+"/bopomo_onion_double.schema.yaml")
shutil.copyfile("./rimefiles/bopomo_onion_double_phrase.txt", "./"+sort_rime+"/"+rime_files+"/bopomo_onion_double_phrase.txt")
shutil.copyfile("./rimefiles/symbols_bpmf_double.schema.yaml", "./"+sort_rime+"/"+rime_files+"/symbols_bpmf_double.schema.yaml")
shutil.copyfile("./rimefiles/element_bopomo_double.yaml", "./"+sort_rime+"/"+rime_files+"/element_bopomo_double.yaml")
shutil.copyfile("./rimefiles/punct_bopomo_double.yaml", "./"+sort_rime+"/"+rime_files+"/punct_bopomo_double.yaml")
shutil.copytree("./rimefiles/custom檔_雙拼注音不開頭簡拼/", "./"+sort_rime+"/"+rime_files+"/custom檔_雙拼注音不開頭簡拼/")
shutil.copytree("./rimefiles/雙拼注音鍵位說明圖示/", "./"+sort_rime+"/其他/雙拼注音鍵位說明圖示/")


#複製檔案(地球拼音洋蔥mix-in版)
shutil.copyfile("./rimefiles/ocm_mixin_jp.dict.yaml", "./"+sort_rime+"/"+rime_files+"/ocm_mixin_jp.dict.yaml")
shutil.copyfile("./rimefiles/ocm_mixin_kr.dict.yaml", "./"+sort_rime+"/"+rime_files+"/ocm_mixin_kr.dict.yaml")
shutil.copyfile("./rimefiles/ocm_mixin_kr_hnc.dict.yaml", "./"+sort_rime+"/"+rime_files+"/ocm_mixin_kr_hnc.dict.yaml")
shutil.copyfile("./rimefiles/ocm_mixin_la.dict.yaml", "./"+sort_rime+"/"+rime_files+"/ocm_mixin_la.dict.yaml")
shutil.copyfile("./rimefiles/terra_pinyin_onion.extended.dict.yaml", "./"+sort_rime+"/"+rime_files+"/terra_pinyin_onion.extended.dict.yaml")
shutil.copyfile("./rimefiles/terra_pinyin_onion.schema.yaml", "./"+sort_rime+"/"+rime_files+"/terra_pinyin_onion.schema.yaml")
shutil.copyfile("./rimefiles/opencc/back_mark_ocm.json", "./"+sort_rime+"/"+rime_files+"/opencc/back_mark_ocm.json")
shutil.copyfile("./rimefiles/opencc/back_mark_ocm.txt", "./"+sort_rime+"/"+rime_files+"/opencc/back_mark_ocm.txt")


#複製檔案(ocm_mount)
shutil.copyfile("./rimefiles/Mount_bopomo.extended.dict.yaml", "./"+sort_rime+"/"+rime_files+"/Mount_bopomo.extended.dict.yaml")
shutil.copyfile("./rimefiles/Mount_bopomo.schema.yaml", "./"+sort_rime+"/"+rime_files+"/Mount_bopomo.schema.yaml")
shutil.copyfile("./rimefiles/Mount_ocm.extended.dict.yaml", "./"+sort_rime+"/"+rime_files+"/Mount_ocm.extended.dict.yaml")
shutil.copyfile("./rimefiles/Mount_ocm.schema.yaml", "./"+sort_rime+"/"+rime_files+"/Mount_ocm.schema.yaml")
shutil.copyfile("./rimefiles/Mount_ocm_encoder.extended.dict.yaml", "./"+sort_rime+"/"+rime_files+"/Mount_ocm_encoder.extended.dict.yaml")
shutil.copyfile("./rimefiles/Mount_ocm_encoder.schema.yaml", "./"+sort_rime+"/"+rime_files+"/Mount_ocm_encoder.schema.yaml")
shutil.copyfile("./rimefiles/Mount_ocm_encoder.custom.yaml", "./"+sort_rime+"/"+rime_files+"/Mount_ocm_encoder.custom.yaml")
shutil.copyfile("./rimefiles/element_ocm.yaml", "./"+sort_rime+"/"+rime_files+"/element_ocm.yaml")
shutil.copyfile("./rimefiles/punct_ovff.dict.yaml", "./"+sort_rime+"/"+rime_files+"/punct_ovff.dict.yaml")
shutil.copyfile("./rimefiles/punct_ovff.schema.yaml", "./"+sort_rime+"/"+rime_files+"/punct_ovff.schema.yaml")
shutil.copyfile("./rimefiles/symbols_ocm.dict.yaml", "./"+sort_rime+"/"+rime_files+"/symbols_ocm.dict.yaml")
shutil.copyfile("./rimefiles/symbols_ocm.schema.yaml", "./"+sort_rime+"/"+rime_files+"/symbols_ocm.schema.yaml")
shutil.copyfile("./rimefiles/ocm_tc_mc.dict.yaml", "./"+sort_rime+"/"+rime_files+"/ocm_tc_mc.dict.yaml")
shutil.copyfile("./rimefiles/uniabcdword.dict.yaml", "./"+sort_rime+"/"+rime_files+"/uniabcdword.dict.yaml")
shutil.copyfile("./rimefiles/kanaword.dict.yaml", "./"+sort_rime+"/"+rime_files+"/kanaword.dict.yaml")
shutil.copyfile("./rimefiles/phrases.ocmtc_essay_mc.dict.yaml", "./"+sort_rime+"/"+rime_files+"/phrases.ocmtc_essay_mc.dict.yaml")


#複製檔案(ocm_plus)
shutil.copyfile("./rimefiles/dif1_cy.schema.yaml", "./"+sort_rime+"/"+rime_files+"/dif1_cy.schema.yaml")
shutil.copyfile("./rimefiles/dif1_fs.schema.yaml", "./"+sort_rime+"/"+rime_files+"/dif1_fs.schema.yaml")
shutil.copyfile("./rimefiles/dif1_gr.schema.yaml", "./"+sort_rime+"/"+rime_files+"/dif1_gr.schema.yaml")
shutil.copyfile("./rimefiles/dif1_jp.extended.dict.yaml", "./"+sort_rime+"/"+rime_files+"/dif1_jp.extended.dict.yaml")
shutil.copyfile("./rimefiles/dif1_jphi.schema.yaml", "./"+sort_rime+"/"+rime_files+"/dif1_jphi.schema.yaml")
shutil.copyfile("./rimefiles/dif1_jpka.schema.yaml", "./"+sort_rime+"/"+rime_files+"/dif1_jpka.schema.yaml")
shutil.copyfile("./rimefiles/dif1_kr.extended.dict.yaml", "./"+sort_rime+"/"+rime_files+"/dif1_kr.extended.dict.yaml")
shutil.copyfile("./rimefiles/dif1_kr.schema.yaml", "./"+sort_rime+"/"+rime_files+"/dif1_kr.schema.yaml")
shutil.copyfile("./rimefiles/dif1_la.extended.dict.yaml", "./"+sort_rime+"/"+rime_files+"/dif1_la.extended.dict.yaml")
shutil.copyfile("./rimefiles/dif1_la.schema.yaml", "./"+sort_rime+"/"+rime_files+"/dif1_la.schema.yaml")
shutil.copyfile("./rimefiles/dif1_phrase.txt", "./"+sort_rime+"/"+rime_files+"/dif1_phrase.txt")
shutil.copyfile("./rimefiles/dif1.extended.dict.yaml", "./"+sort_rime+"/"+rime_files+"/dif1.extended.dict.yaml")
shutil.copyfile("./rimefiles/dif1.schema.yaml", "./"+sort_rime+"/"+rime_files+"/dif1.schema.yaml")
shutil.copyfile("./rimefiles/punct_ocm.yaml", "./"+sort_rime+"/"+rime_files+"/punct_ocm.yaml")


#複製檔案(ocm_mixin)
shutil.copyfile("./rimefiles/ocm_mixin_cyrillic.schema.yaml", "./"+sort_rime+"/"+rime_files+"/ocm_mixin_cyrillic.schema.yaml")
shutil.copyfile("./rimefiles/ocm_mixin_fullshape.schema.yaml", "./"+sort_rime+"/"+rime_files+"/ocm_mixin_fullshape.schema.yaml")
shutil.copyfile("./rimefiles/ocm_mixin_greek.schema.yaml", "./"+sort_rime+"/"+rime_files+"/ocm_mixin_greek.schema.yaml")
shutil.copyfile("./rimefiles/ocm_mixin_phrase.txt", "./"+sort_rime+"/"+rime_files+"/ocm_mixin_phrase.txt")
shutil.copyfile("./rimefiles/ocm_mixin.extended.dict.yaml", "./"+sort_rime+"/"+rime_files+"/ocm_mixin.extended.dict.yaml")
shutil.copyfile("./rimefiles/ocm_mixin.schema.yaml", "./"+sort_rime+"/"+rime_files+"/ocm_mixin.schema.yaml")
# shutil.copyfile("./rimefiles/ocm_mixin_lua/rime.lua", "./"+sort_rime+"/"+rime_files+"/rime.lua")
# shutil.copyfile("./rimefiles/opencc/back_mark_ocm.json", "./"+sort_rime+"/"+rime_files+"/opencc/back_mark_ocm.json")
# shutil.copyfile("./rimefiles/opencc/back_mark_ocm.txt", "./"+sort_rime+"/"+rime_files+"/opencc/back_mark_ocm.txt")
shutil.copyfile("./rimefiles/symbols-mark.dict.yaml", "./"+sort_rime+"/"+rime_files+"/symbols-mark.dict.yaml")
shutil.copyfile("./rimefiles/symbols-mark.schema.yaml", "./"+sort_rime+"/"+rime_files+"/symbols-mark.schema.yaml")


#複製檔案(洋蔥行列30)
shutil.copyfile("./rimefiles/onion-array30.schema.yaml", "./"+sort_rime+"/"+rime_files+"/onion-array30.schema.yaml")
shutil.copyfile("./rimefiles/onion-array30-wsymbols.schema.yaml", "./"+sort_rime+"/"+rime_files+"/onion-array30-wsymbols.schema.yaml")
shutil.copyfile("./rimefiles/onion-array30.extended.dict.yaml", "./"+sort_rime+"/"+rime_files+"/onion-array30.extended.dict.yaml")
shutil.copyfile("./rimefiles/onion-array30-wsymbols.dict.yaml", "./"+sort_rime+"/"+rime_files+"/onion-array30-wsymbols.dict.yaml")
shutil.copyfile("./rimefiles/onion-array30-special.dict.yaml", "./"+sort_rime+"/"+rime_files+"/onion-array30-special.dict.yaml")
shutil.copyfile("./rimefiles/onion-array30-shortcode.dict.yaml", "./"+sort_rime+"/"+rime_files+"/onion-array30-shortcode.dict.yaml")
shutil.copyfile("./rimefiles/onion-array30-phrases.dict.yaml", "./"+sort_rime+"/"+rime_files+"/onion-array30-phrases.dict.yaml")
shutil.copyfile("./rimefiles/onion-array30-generally.dict.yaml", "./"+sort_rime+"/"+rime_files+"/onion-array30-generally.dict.yaml")
shutil.copytree("./rimefiles/行列30碼表_20230211版/", "./"+sort_rime+"/"+rime_files+"/行列30碼表_20230211版/")


#複製檔案(洋蔥行列10)
shutil.copyfile("./rimefiles/onion-array10.schema.yaml", "./"+sort_rime+"/"+rime_files+"/onion-array10.schema.yaml")
shutil.copyfile("./rimefiles/onion-array10.extended.dict.yaml", "./"+sort_rime+"/"+rime_files+"/onion-array10.extended.dict.yaml")
shutil.copyfile("./rimefiles/onion-array10-symbols.dict.yaml", "./"+sort_rime+"/"+rime_files+"/onion-array10-symbols.dict.yaml")
shutil.copyfile("./rimefiles/onion-array10-symbols-prefix.dict.yaml", "./"+sort_rime+"/"+rime_files+"/onion-array10-symbols-prefix.dict.yaml")
shutil.copyfile("./rimefiles/onion-array10-generally-a.dict.yaml", "./"+sort_rime+"/"+rime_files+"/onion-array10-generally-a.dict.yaml")
shutil.copyfile("./rimefiles/onion-array10-generally-b.dict.yaml", "./"+sort_rime+"/"+rime_files+"/onion-array10-generally-b.dict.yaml")
shutil.copyfile("./rimefiles/onion-array10-generally-c.dict.yaml", "./"+sort_rime+"/"+rime_files+"/onion-array10-generally-c.dict.yaml")
shutil.copyfile("./rimefiles/onion-array10-and-bpmf.schema.yaml", "./"+sort_rime+"/"+rime_files+"/onion-array10-and-bpmf.schema.yaml")


#全部方案開啟default.custom檔
shutil.copyfile("./rimefiles/其他/全部方案開啟default.custom檔/default.custom.yaml", "./"+sort_rime+"/"+rime_files+"/default.custom.yaml")


#各方案default.custom
shutil.copytree("./rimefiles/各方案default.custom/地球拼音洋蔥mix-in版_custom/", "./"+sort_rime+"/其他/各方案default.custom/地球拼音洋蔥mix-in版_custom/")
shutil.copytree("./rimefiles/各方案default.custom/注音洋蔥mixin版_custom/", "./"+sort_rime+"/其他/各方案default.custom/注音洋蔥mixin版_custom/")
shutil.copytree("./rimefiles/各方案default.custom/注音洋蔥plus版_custom/", "./"+sort_rime+"/其他/各方案default.custom/注音洋蔥plus版_custom/")
shutil.copytree("./rimefiles/各方案default.custom/注音洋蔥純注音版_custom/", "./"+sort_rime+"/其他/各方案default.custom/注音洋蔥純注音版_custom/")
shutil.copytree("./rimefiles/各方案default.custom/注音洋蔥雙拼版_custom/", "./"+sort_rime+"/其他/各方案default.custom/注音洋蔥雙拼版_custom/")

shutil.copytree("./rimefiles/各方案default.custom/洋蔥行列30_custom/", "./"+sort_rime+"/其他/各方案default.custom/洋蔥行列30_custom/")
shutil.copytree("./rimefiles/各方案default.custom/洋蔥行列10_custom/", "./"+sort_rime+"/其他/各方案default.custom/洋蔥行列10_custom/")

shutil.copytree("./rimefiles/各方案default.custom/ocm_mixin_custom/", "./"+sort_rime+"/其他/各方案default.custom/ocm_mixin_custom/")
shutil.copytree("./rimefiles/各方案default.custom/ocm_mount_custom/", "./"+sort_rime+"/其他/各方案default.custom/ocm_mount_custom/")
shutil.copytree("./rimefiles/各方案default.custom/ocm_plus_custom/", "./"+sort_rime+"/其他/各方案default.custom/ocm_plus_custom/")


#其他
shutil.copytree("./rimefiles/其他/Mac鼠鬚管外觀設定檔/", "./"+sort_rime+"/其他/Mac鼠鬚管外觀設定檔/")
shutil.copytree("./rimefiles/其他/OpenCC_ocd_64位元/", "./"+sort_rime+"/其他/OpenCC_ocd_64位元/")
shutil.copytree("./rimefiles/其他/Win小狼毫外觀設定檔/", "./"+sort_rime+"/其他/Win小狼毫外觀設定檔/")

# shutil.copytree("./rimefiles/其他/OpenCC_ocd_64位元/", "./"+sort_rime+"/ocm/OpenCC_ocd_64位元/")
# shutil.copytree("./rimefiles/custom檔_舊版防崩潰/ocm_防崩潰：Win必加，Mac勿加/", "./"+sort_rime+"/ocm/ocm_防崩潰：Win必加，Mac勿加/")
# shutil.copyfile("./rimefiles/custom檔_舊版防崩潰/easy_en_super_防崩潰：Win必加，Mac勿加/easy_en_super.custom.yaml", "./"+sort_rime+"/ocm/ocm_防崩潰：Win必加，Mac勿加/easy_en_super.custom.yaml")
# shutil.copyfile("./rimefiles/custom檔_舊版防崩潰/easy_en_lower_防崩潰：Win必加，Mac勿加/easy_en_lower.custom.yaml", "./"+sort_rime+"/ocm/ocm_防崩潰：Win必加，Mac勿加/easy_en_lower.custom.yaml")


#主程式
shutil.copytree("./rimefiles/主程式/", "./"+sort_rime+"/主程式/")


#增加日期
localtime=time.strftime("%Y%m%d", time.localtime())
os.rename("./"+sort_rime+"/"+rime_files+"/", "./"+sort_rime+"/"+rime_files+"_"+localtime)
os.rename("./"+sort_rime+"/", "./"+the_name+"_"+localtime)



